import StringDiagrams.Signature
import StringDiagrams.Syntax
import StringDiagrams.Presentation
import StringDiagrams.Interpretation
import StringDiagrams.Whisker
import StringDiagrams.Generation
import StringDiagrams.Interchange
import StringDiagrams.Grading
import StringDiagrams.Super.Basic
import StringDiagrams.Super.Functor
import StringDiagrams.Super.Monoidal
import StringDiagrams.Super.Bicategory
import StringDiagrams.Super.Presented
import StringDiagrams.Super.Parity
import StringDiagrams.Super.Supernatural
import StringDiagrams.Super.PiCategory
import StringDiagrams.Super.Pi
import StringDiagrams.Super.Envelope
import StringDiagrams.Super.Underlying
import StringDiagrams.Super.Associated
import StringDiagrams.Super.MonoidalEnvelope
import StringDiagrams.Super.MonoidalPi
import StringDiagrams.Super.SVec
import StringDiagrams.Super.K0
import StringDiagrams.Super.SKar
import StringDiagrams.Super.Superalgebra
import StringDiagrams.Super.Superbimodule
import StringDiagrams.Super.KaroubiMonoidal
import StringDiagrams.Monoidal
import StringDiagrams.Derivation
import StringDiagrams.Horizontal
import StringDiagrams.Bicategory
import StringDiagrams.LocalInterpretation
import StringDiagrams.DSL.Basic
import StringDiagrams.Render.SVG
import StringDiagrams.Render.TikZ
import StringDiagrams.Examples.Exterior
import StringDiagrams.Examples.FreeDots
import StringDiagrams.Examples.FreeDots.Representation
import StringDiagrams.Examples.Derivation
import StringDiagrams.Examples.TemperleyLieb
import StringDiagrams.Examples.TemperleyLieb.FarCommutativity
import StringDiagrams.Examples.TemperleyLieb.Representation
import StringDiagrams.Tactic.WordRw
import StringDiagrams.Examples.Grading
import StringDiagrams.Examples.TemperleyLiebMonoidal
import StringDiagrams.Examples.WeightedBubbles
import StringDiagrams.Biadjunction.Basic
import StringDiagrams.Biadjunction.Conjugate
import StringDiagrams.Biadjunction.Cyclic
import StringDiagrams.Biadjunction.Linear
import StringDiagrams.Biadjunction.Trace
import StringDiagrams.Biadjunction.Pivotal
import StringDiagrams.Biadjunction.Monoidal
import StringDiagrams.Biadjunction.Zigzag
import StringDiagrams.Biadjunction.Words
import StringDiagrams.Biadjunction.Presented
import StringDiagrams.Biadjunction.PivotalExtension
import StringDiagrams.Examples.WalkingBiadjunction
import StringDiagrams.Examples.OddBrauer
import StringDiagrams.Examples.PiEnvelope
import StringDiagrams.Biadjunction.NestedCups
import StringDiagrams.Biadjunction.PivotalInclusion
import StringDiagrams.Examples.TwoStrandGenerator

/-!
# StringDiagrams

A Lean 4 library for diagrammatic reasoning: typed diagram syntax, presentations by generators and relations, interpretations, and Lean-checked diagram rewriting.
-/
