import StringDiagrams.Interpretation

/-!
# The nilHecke algebras as a presented linear category

The nilHecke algebra `NH_n` is the endomorphism algebra of `n` strands in the linear
monoidal category with one strand colour, generated by a dot and a crossing, subject to

* `ψ² = 0` (a double crossing vanishes),
* `ψ₁ψ₂ψ₁ = ψ₂ψ₁ψ₂` (braid relation),
* `x_a ψ_a − ψ_a x_{a+1} = 1` and `ψ_a x_a − x_{a+1} ψ_a = 1` (dot slides),

together with the interchange law (far commutativity).

Source: M. Khovanov, A. D. Lauda, *A diagrammatic approach to categorification of quantum
groups I*, arXiv:0803.4121v2, §2.2, Example 3 (p. 10), relations (2.17)–(2.19) and the
displayed nilHecke relations. There `∂_a` is the crossing of strands `a` and `a+1` and
products are composition of operators (`fg` means `g` first). Here strands are numbered
from `0`: `ψ n a` is the crossing of strands `a` and `a+1` among `n`, `x n a` is a dot on
strand `a` (the paper's `∂_{a+1}` and `x_{a+1}`), and products in `End` are composition of
operators (`f * g = g ≫ f`, i.e. `g` below `f`).

## Main declarations

* `NilHecke.sig`, `NilHecke.pres R`: the signature and the presentation over a commutative
  ring `R`; `NilHecke.NH R` is the presented category and `NilHecke.strands n` the object
  of `n` strands.
* `NilHecke.x n a`, `NilHecke.ψ n a : End (NH.obj R n)`: a dot and a crossing at a symbolic
  position in a symbolic width (zero when out of range).
* The nilHecke relations for all `n` and all positions: `ψ_mul_ψ`, `ψ_braid`,
  `x_mul_ψ_sub_ψ_mul_x`, `ψ_mul_x_sub_x_mul_ψ`, and far commutativity `x_mul_x_comm`,
  `x_mul_ψ_comm`, `ψ_mul_ψ_comm`.
-/

noncomputable section

namespace StringDiagrams.NilHecke

open CategoryTheory

/-- The generators: a dot and a crossing. -/
inductive Gen
  | dot
  | cross
  deriving DecidableEq

/-- Number of strands at the bottom (and top) of a generator. -/
def Gen.arity : Gen → ℕ
  | .dot => 1
  | .cross => 2

/-- The nilHecke signature: one region, one colour, a dot and a crossing. -/
def sig : Signature where
  Region := Unit
  Colour := Unit
  colourSrc _ := ()
  colourTgt _ := ()
  Gen := Gen
  dom g := List.replicate g.arity ()
  cod g := List.replicate g.arity ()
  left _ := ()
  right _ := ()

instance : Subsingleton sig.Region := inferInstanceAs (Subsingleton Unit)

/-- `n` strands. -/
def strands (n : ℕ) : Obj sig := ⟨(), List.replicate n ()⟩

theorem list_punit_ext {l₁ l₂ : List Unit} (h : l₁.length = l₂.length) : l₁ = l₂ := by
  induction l₁ generalizing l₂ with
  | nil => cases l₂ with
    | nil => rfl
    | cons _ _ => simp at h
  | cons a l ih => cases l₂ with
    | nil => simp at h
    | cons b l₂ => rw [ih (by simpa using h)]

theorem obj_ext {a b : Obj sig} (h : a.word.length = b.word.length) : a = b :=
  Obj.ext (Subsingleton.elim (α := Unit) _ _) (list_punit_ext h)

theorem layer_ext {L₁ L₂ : Layer sig} (hl : L₁.left.length = L₂.left.length)
    (hg : L₁.gen = L₂.gen) (hr : L₁.right.length = L₂.right.length) : L₁ = L₂ :=
  Layer.ext (Subsingleton.elim (α := Unit) _ _) (list_punit_ext hl) hg (list_punit_ext hr)

/-- The generator `g` with `i` strands to its left, in a diagram on `n` strands. -/
def lay (n i : ℕ) (g : Gen) : Layer sig :=
  ⟨(), List.replicate i (), g, List.replicate (n - i - g.arity) ()⟩

theorem lay_valid (n i : ℕ) (g : Gen) : (lay n i g).Valid := Layer.valid_of_subsingleton _

theorem lay_dom {n i : ℕ} {g : Gen} (h : i + g.arity ≤ n) : (lay n i g).dom = strands n :=
  obj_ext (by simp [lay, Layer.dom, strands, sig]; omega)

theorem lay_cod {n i : ℕ} {g : Gen} (h : i + g.arity ≤ n) : (lay n i g).cod = strands n :=
  obj_ext (by simp [lay, Layer.cod, strands, sig]; omega)

/-- The layer `lay n i g` as an endomorphism of `n` strands in the free 2-category. -/
def dlay {n i : ℕ} {g : Gen} (h : i + g.arity ≤ n) : strands n ⟶ strands n :=
  Diagram.layer (lay n i g) (lay_valid n i g) (lay_dom h) (lay_cod h)

/-! ## The presentation -/

/-- The defining relations (besides interchange). -/
inductive Rel
  | crossSq
  | braid
  | slideA
  | slideB

/-- Width of the defining relations. -/
def Rel.width : Rel → ℕ
  | .crossSq => 2
  | .braid => 3
  | .slideA => 2
  | .slideB => 2

variable (R : Type*) [CommRing R]

open LinDiagram in
/-- The defining relations, in the free 2-category (`f ≫ g` means `f` below `g`):
* `crossSq`: `ψ₀ ≫ ψ₀`;
* `braid`: `ψ₀ ≫ ψ₁ ≫ ψ₀ - ψ₁ ≫ ψ₀ ≫ ψ₁`;
* `slideA` (`x_a ψ_a - ψ_a x_{a+1} = 1`): `ψ₀ ≫ x₀ - x₁ ≫ ψ₀ - 1`;
* `slideB` (`ψ_a x_a - x_{a+1} ψ_a = 1`): `x₀ ≫ ψ₀ - ψ₀ ≫ x₁ - 1`. -/
def relation : (r : Rel) → LinDiagram R (strands r.width) (strands r.width)
  | .crossSq => of (dlay (g := .cross) (i := 0) (by decide) ≫ dlay (g := .cross) (i := 0) (by decide))
  | .braid =>
      of (dlay (g := .cross) (i := 0) (by decide) ≫ dlay (g := .cross) (i := 1) (by decide) ≫
          dlay (g := .cross) (i := 0) (by decide)) -
        of (dlay (g := .cross) (i := 1) (by decide) ≫ dlay (g := .cross) (i := 0) (by decide) ≫
          dlay (g := .cross) (i := 1) (by decide))
  | .slideA =>
      of (dlay (g := .cross) (i := 0) (by decide) ≫ dlay (g := .dot) (i := 0) (by decide)) -
        of (dlay (g := .dot) (i := 1) (by decide) ≫ dlay (g := .cross) (i := 0) (by decide)) -
        of (𝟙 _)
  | .slideB =>
      of (dlay (g := .dot) (i := 0) (by decide) ≫ dlay (g := .cross) (i := 0) (by decide)) -
        of (dlay (g := .cross) (i := 0) (by decide) ≫ dlay (g := .dot) (i := 1) (by decide)) -
        of (𝟙 _)

/-- The nilHecke presentation over `R`. -/
def pres : Presentation sig R where
  Rel := Rel
  dom r := strands r.width
  cod r := strands r.width
  rel := relation R

/-- The nilHecke category over `R`: its endomorphism algebra of `n` strands is `NH_n`. -/
abbrev NH : Type _ := (pres R).Presented

/-- The object of `n` strands in `NH R`. -/
abbrev NH.obj (n : ℕ) : NH R := (pres R).obj (strands n)

/-- A dot on strand `i` of `n` (zero if `i ≥ n`). -/
def x (n i : ℕ) : End (NH.obj R n) :=
  if h : i < n then (pres R).diag (dlay (g := .dot) h) else 0

/-- The crossing of strands `i` and `i + 1` of `n` (zero if `i + 1 ≥ n`). -/
def ψ (n i : ℕ) : End (NH.obj R n) :=
  if h : i + 1 < n then (pres R).diag (dlay (g := .cross) h) else 0

end StringDiagrams.NilHecke

end
