import Mathlib

/-!
# The polynomial representation of the nilHecke algebra

This file constructs the divided difference operators on the polynomial ring
`MvPolynomial ℕ R` in the variables `X 0, X 1, X 2, …`, over an arbitrary commutative ring `R`,
and proves that together with the operators of multiplication by the variables they satisfy the
defining relations of the nilHecke algebra, at every index.

## Source

M. Khovanov and A. Lauda, *A diagrammatic approach to categorification of quantum groups I*,
arXiv:0803.4121v2, §2.2, Example 3 (p. 10). There the nilHecke ring `NH_m` is presented as the
ring of endomorphisms of `ℤ[x_1, …, x_m]` generated by multiplication by `x_a` and the divided
difference operators `∂_a f = (f - s_a f) / (x_a - x_{a+1})`, `1 ≤ a ≤ m - 1`, subject to
* `x_a x_b = x_b x_a`;
* `∂_a x_b = x_b ∂_a` and `∂_a ∂_b = ∂_b ∂_a` for `|a - b| > 1`;
* `∂_a² = 0` and `∂_a ∂_{a+1} ∂_a = ∂_{a+1} ∂_a ∂_{a+1}`;
* `x_a ∂_a - ∂_a x_{a+1} = 1` and `∂_a x_a - x_{a+1} ∂_a = 1`,
where products are composition of operators and `x_a` denotes multiplication by `x_a`.

## Conventions

* Indexing is `0`-based: the paper's variable `x_a` is `X (a - 1)` here, and the paper's `∂_a`,
  `s_a` are `divDiff (a - 1)`, `swapVars (a - 1)`. Thus `divDiff i` and `swapVars i` involve the
  variables `X i` and `X (i + 1)`.
* We work with countably many variables, so the relations are stated for all indices at once;
  the coefficient ring is an arbitrary commutative ring `R` (the paper uses `R = ℤ`).
* Products of operators are `LinearMap` compositions `∘ₗ`, read right to left as in the paper.
* The relation `∂_a x_b = x_b ∂_a` is proved under the weaker hypothesis `b ∉ {a, a + 1}`.

## Construction

`divDiff i` is defined without division. Let `T` be a new variable and let
`taylorShift i : MvPolynomial ℕ R →ₐ[R] (MvPolynomial ℕ R)[T]` substitute
`X i ↦ X (i + 1) + T` and fix the other variables. The polynomial
`F = taylorShift i f - taylorShift i (swapVars i f)` has constant term `0`, and `divDiff i f`
is `F / T` (the coefficient shift `Polynomial.divX`) evaluated at `T = X i - X (i + 1)`.
The characterization `mul_divDiff` follows, and every other identity is derived from it by
cancelling the non-zero-divisors `X i - X j` (`i ≠ j`), which are non-zero-divisors over every
commutative ring (`eq_zero_of_X_sub_X_mul_eq_zero`).

## Main declarations

* `swapVars i`: the algebra automorphism exchanging `X i` and `X (i + 1)`.
* `divDiff i`: the divided difference operator, an `R`-linear endomorphism.
* `mulX i`: multiplication by `X i`, as an `R`-linear endomorphism.
* `mul_divDiff`: `(X i - X (i + 1)) * divDiff i f = f - swapVars i f`.
* `divDiff_X_self`, `divDiff_X_succ`, `divDiff_X_of_ne`, `divDiff_mul` (twisted Leibniz rule),
  `divDiff_of_swap_eq`, `swapVars_divDiff`.
* The nilHecke relations: `mulX_comm`, `mulX_divDiff_comm`, `divDiff_comm`, `divDiff_divDiff`,
  `divDiff_braid`, `mulX_divDiff_sub`, `divDiff_mulX_sub`, with pointwise forms
  `divDiff_X_mul_of_ne`, `divDiff_comm_apply`, `divDiff_divDiff_apply`, `divDiff_braid_apply`,
  `divDiff_X_self_mul`, `divDiff_X_succ_mul`.
* `vandermonde_mul_divDiff_braid_left`, `vandermonde_mul_divDiff_braid_right`: both sides of the
  braid relation, multiplied by the Vandermonde product in `X i, X (i + 1), X (i + 2)`, equal the
  alternating sum over the permutations of these three variables.
-/

noncomputable section

namespace StringDiagrams.NilHecke

open MvPolynomial

variable {R : Type*} [CommRing R]

/-! ### The transpositions of adjacent variables -/

/-- The `R`-algebra automorphism of `MvPolynomial ℕ R` exchanging `X i` and `X (i + 1)`
(the paper's `s_{i+1}`). -/
def swapVars (i : ℕ) : MvPolynomial ℕ R →ₐ[R] MvPolynomial ℕ R :=
  rename (Equiv.swap i (i + 1))

theorem swapVars_X (i j : ℕ) :
    swapVars (R := R) i (X j) = X (Equiv.swap i (i + 1) j) := rename_X _ _

@[simp] theorem swapVars_X_self (i : ℕ) : swapVars (R := R) i (X i) = X (i + 1) := by
  simp [swapVars_X]

@[simp] theorem swapVars_X_succ (i : ℕ) : swapVars (R := R) i (X (i + 1)) = X i := by
  simp [swapVars_X]

theorem swapVars_X_of_ne {i j : ℕ} (h : j ≠ i) (h' : j ≠ i + 1) :
    swapVars (R := R) i (X j) = X j := by
  rw [swapVars_X, Equiv.swap_apply_of_ne_of_ne h h']

/-- `swapVars i` is an involution. -/
@[simp] theorem swapVars_swapVars (i : ℕ) (f : MvPolynomial ℕ R) :
    swapVars i (swapVars i f) = f := by
  have : (⇑(Equiv.swap i (i + 1)) ∘ ⇑(Equiv.swap i (i + 1))) = id :=
    funext fun k => Equiv.swap_apply_self _ _ _
  rw [swapVars, rename_rename, this, rename_id, AlgHom.id_apply]

/-! ### Construction of the divided difference operator -/

/-- The substitution `X i ↦ X (i + 1) + T` into the polynomial ring in `T` over
`MvPolynomial ℕ R`, fixing every other variable. -/
def taylorShift (i : ℕ) : MvPolynomial ℕ R →ₐ[R] Polynomial (MvPolynomial ℕ R) :=
  aeval fun j => if j = i then Polynomial.C (X (i + 1)) + Polynomial.X else Polynomial.C (X j)

/-- Evaluating `taylorShift i f` at `T = X i - X (i + 1)` recovers `f`. -/
theorem eval_taylorShift (i : ℕ) (f : MvPolynomial ℕ R) :
    (taylorShift i f).eval (X i - X (i + 1)) = f := by
  have : ((Polynomial.aeval (X i - X (i + 1) : MvPolynomial ℕ R)).restrictScalars R).comp
      (taylorShift i) = AlgHom.id R _ := by
    apply MvPolynomial.algHom_ext
    intro j
    by_cases hj : j = i
    · subst hj; simp [taylorShift]
    · simp [taylorShift, hj]
  simpa [Polynomial.coe_aeval_eq_eval] using congrArg (fun g => g f) this

/-- `taylorShift i f` and `taylorShift i (swapVars i f)` have the same constant term. -/
theorem coeff_zero_taylorShift_swapVars (i : ℕ) (f : MvPolynomial ℕ R) :
    (taylorShift i (swapVars i f)).coeff 0 = (taylorShift i f).coeff 0 := by
  have : ((Polynomial.aeval (0 : MvPolynomial ℕ R)).restrictScalars R).comp
      ((taylorShift i).comp (swapVars i)) =
      ((Polynomial.aeval (0 : MvPolynomial ℕ R)).restrictScalars R).comp (taylorShift i) := by
    apply MvPolynomial.algHom_ext
    intro j
    by_cases hj : j = i
    · subst hj; simp [taylorShift]
    by_cases hj' : j = i + 1
    · subst hj'; simp [taylorShift]
    · simp [taylorShift, swapVars_X_of_ne hj hj', hj]
  simpa [Polynomial.coe_aeval_eq_eval, Polynomial.coeff_zero_eq_eval_zero]
    using congrArg (fun g => g f) this

private theorem divX_smul (c : R) (p : Polynomial (MvPolynomial ℕ R)) :
    Polynomial.divX (c • p) = c • Polynomial.divX p := by
  ext n; simp [Polynomial.coeff_divX]

/-- The divided difference operator `∂_i f = (f - s_i f) / (X i - X (i + 1))` (the paper's
`∂_{i+1}`), defined without division; see the module docstring. -/
def divDiff (i : ℕ) : MvPolynomial ℕ R →ₗ[R] MvPolynomial ℕ R where
  toFun f :=
    (Polynomial.divX (taylorShift i f - taylorShift i (swapVars i f))).eval (X i - X (i + 1))
  map_add' f g := by
    simp only [map_add]
    rw [add_sub_add_comm, Polynomial.divX_add, Polynomial.eval_add]
  map_smul' c f := by
    simp only [map_smul, ← smul_sub, divX_smul, Polynomial.eval_smul, RingHom.id_apply]

/-- The characterization of the divided difference operator. -/
theorem mul_divDiff (i : ℕ) (f : MvPolynomial ℕ R) :
    (X i - X (i + 1)) * divDiff i f = f - swapVars i f := by
  have h := Polynomial.divX_mul_X_add (taylorShift i f - taylorShift i (swapVars i f))
  have h2 := congrArg (Polynomial.eval (X i - X (i + 1) : MvPolynomial ℕ R)) h
  simp only [Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_X, Polynomial.eval_C,
    Polynomial.eval_sub, eval_taylorShift, Polynomial.coeff_sub, coeff_zero_taylorShift_swapVars,
    sub_self, add_zero] at h2
  rw [← h2, mul_comm]
  rfl

/-- `X i - X j` is a non-zero-divisor for `i ≠ j`, over any commutative ring. -/
theorem eq_zero_of_X_sub_X_mul_eq_zero {i j : ℕ} (hij : i ≠ j) {p : MvPolynomial ℕ R}
    (h : (X i - X j) * p = 0) : p = 0 := by
  classical
  let τ : MvPolynomial ℕ R →ₐ[R] MvPolynomial ℕ R :=
    aeval fun k => if k = i then X i + X j else X k
  let τ' : MvPolynomial ℕ R →ₐ[R] MvPolynomial ℕ R :=
    aeval fun k => if k = i then X i - X j else X k
  have hτ : τ'.comp τ = AlgHom.id R _ := by
    apply MvPolynomial.algHom_ext
    intro k
    by_cases hk : k = i
    · subst hk; simp [τ, τ', Ne.symm hij]
    · simp [τ, τ', hk]
  have h1 : X i * τ p = 0 := by
    have := congrArg τ h
    simpa [τ, Ne.symm hij] using this
  have h2 : τ p = 0 := by
    ext m
    have := congrArg (coeff (Finsupp.single i 1 + m)) h1
    simpa [coeff_X_mul] using this
  have := congrArg (fun g => g p) hτ
  simpa [h2] using this.symm

/-- Cancellation of `X i - X j` for `i ≠ j`, over any commutative ring. -/
theorem X_sub_X_mul_cancel {i j : ℕ} (hij : i ≠ j) {p q : MvPolynomial ℕ R}
    (h : (X i - X j) * p = (X i - X j) * q) : p = q :=
  sub_eq_zero.mp (eq_zero_of_X_sub_X_mul_eq_zero hij (by rw [mul_sub, h, sub_self]))

/-! ### Basic properties of `divDiff` -/

/-- `divDiff i f` is the unique `g` with `(X i - X (i + 1)) * g = f - swapVars i f`. -/
theorem divDiff_eq_of_mul {i : ℕ} {f g : MvPolynomial ℕ R}
    (h : (X i - X (i + 1)) * g = f - swapVars i f) : divDiff i f = g :=
  X_sub_X_mul_cancel (i := i) (j := i + 1) (by omega) (by rw [mul_divDiff, h])

@[simp] theorem divDiff_X_self (i : ℕ) : divDiff (R := R) i (X i) = 1 :=
  divDiff_eq_of_mul (by simp)

@[simp] theorem divDiff_X_succ (i : ℕ) : divDiff (R := R) i (X (i + 1)) = -1 :=
  divDiff_eq_of_mul (by simp)

theorem divDiff_X_of_ne {i j : ℕ} (h : j ≠ i) (h' : j ≠ i + 1) :
    divDiff (R := R) i (X j) = 0 :=
  divDiff_eq_of_mul (by simp [swapVars_X_of_ne h h'])

/-- The divided difference operator kills `swapVars`-invariant polynomials. -/
theorem divDiff_of_swap_eq {i : ℕ} {f : MvPolynomial ℕ R} (h : swapVars i f = f) :
    divDiff i f = 0 :=
  divDiff_eq_of_mul (by simp [h])

/-- The twisted Leibniz rule `∂(fg) = ∂f · g + s(f) · ∂g`. -/
theorem divDiff_mul (i : ℕ) (f g : MvPolynomial ℕ R) :
    divDiff i (f * g) = divDiff i f * g + swapVars i f * divDiff i g := by
  apply divDiff_eq_of_mul
  rw [mul_add, ← mul_assoc, mul_divDiff, mul_left_comm, mul_divDiff, map_mul]
  ring

/-- The image of the divided difference operator is `swapVars`-invariant. -/
@[simp] theorem swapVars_divDiff (i : ℕ) (f : MvPolynomial ℕ R) :
    swapVars i (divDiff i f) = divDiff i f := by
  apply X_sub_X_mul_cancel (show i ≠ i + 1 by omega)
  have h := congrArg (swapVars i) (mul_divDiff i f)
  simp only [map_mul, map_sub, swapVars_X_self, swapVars_X_succ, swapVars_swapVars] at h
  linear_combination -h - mul_divDiff i f

/-- `∂_i ∂_i = 0`, pointwise. -/
@[simp] theorem divDiff_divDiff_apply (i : ℕ) (f : MvPolynomial ℕ R) :
    divDiff i (divDiff i f) = 0 :=
  divDiff_of_swap_eq (swapVars_divDiff i f)

/-- The divided difference operator is linear over `swapVars`-invariant polynomials. -/
theorem divDiff_mul_of_swap_eq {i : ℕ} {g : MvPolynomial ℕ R} (h : swapVars i g = g)
    (f : MvPolynomial ℕ R) : divDiff i (g * f) = g * divDiff i f := by
  rw [divDiff_mul, divDiff_of_swap_eq h, zero_mul, zero_add, h]

theorem divDiff_X_mul_of_ne {i j : ℕ} (h : j ≠ i) (h' : j ≠ i + 1) (f : MvPolynomial ℕ R) :
    divDiff i (X j * f) = X j * divDiff i f :=
  divDiff_mul_of_swap_eq (swapVars_X_of_ne h h') f

theorem divDiff_X_self_mul (i : ℕ) (f : MvPolynomial ℕ R) :
    divDiff i (X i * f) = f + X (i + 1) * divDiff i f := by
  simp [divDiff_mul]

theorem divDiff_X_succ_mul (i : ℕ) (f : MvPolynomial ℕ R) :
    divDiff i (X (i + 1) * f) = -f + X i * divDiff i f := by
  simp [divDiff_mul]

/-- Transpositions of disjoint pairs of adjacent variables commute. -/
theorem swapVars_comm {i j : ℕ} (h : i + 1 < j ∨ j + 1 < i) (f : MvPolynomial ℕ R) :
    swapVars i (swapVars j f) = swapVars j (swapVars i f) := by
  simp only [swapVars, rename_rename]
  congr 2
  funext k
  simp only [Function.comp_apply, Equiv.swap_apply_def]
  split_ifs <;> omega

/-- `swapVars j` commutes with `divDiff i` when the index pairs are disjoint. -/
theorem swapVars_divDiff_of_far {i j : ℕ} (h : i + 1 < j ∨ j + 1 < i) (f : MvPolynomial ℕ R) :
    swapVars j (divDiff i f) = divDiff i (swapVars j f) := by
  symm
  apply divDiff_eq_of_mul
  have h1 := congrArg (swapVars j) (mul_divDiff i f)
  rw [map_mul, map_sub, map_sub, swapVars_X_of_ne (by omega) (by omega),
    swapVars_X_of_ne (by omega) (by omega), ← swapVars_comm h] at h1
  exact h1

/-- Divided differences at distant indices commute, pointwise. -/
theorem divDiff_comm_apply {i j : ℕ} (h : i + 1 < j ∨ j + 1 < i) (f : MvPolynomial ℕ R) :
    divDiff i (divDiff j f) = divDiff j (divDiff i f) := by
  apply X_sub_X_mul_cancel (show j ≠ j + 1 by omega)
  have hs : swapVars i (X j - X (j + 1) : MvPolynomial ℕ R) = X j - X (j + 1) := by
    rw [map_sub, swapVars_X_of_ne (by omega) (by omega), swapVars_X_of_ne (by omega) (by omega)]
  rw [← divDiff_mul_of_swap_eq hs, mul_divDiff, mul_divDiff, map_sub,
    swapVars_divDiff_of_far (by omega)]

/-! ### The braid relation -/

/-- The Vandermonde product times `∂_i ∂_{i+1} ∂_i f` is the alternating sum of `w f` over the
permutations `w` of `X i, X (i + 1), X (i + 2)`, written with `s = swapVars i`,
`t = swapVars (i + 1)` as `f - s f - t f + t s f + s t f - s t s f`. -/
theorem vandermonde_mul_divDiff_braid_left (i : ℕ) (f : MvPolynomial ℕ R) :
    (X i - X (i + 1)) * (X i - X (i + 2)) * (X (i + 1) - X (i + 2)) *
        divDiff i (divDiff (i + 1) (divDiff i f)) =
      f - swapVars i f - swapVars (i + 1) f + swapVars (i + 1) (swapVars i f) +
        swapVars i (swapVars (i + 1) f) - swapVars i (swapVars (i + 1) (swapVars i f)) := by
  have s0 : swapVars (R := R) i (X i) = X (i + 1) := swapVars_X_self i
  have s1 : swapVars (R := R) i (X (i + 1)) = X i := swapVars_X_succ i
  have s2 : swapVars (R := R) i (X (i + 2)) = X (i + 2) := swapVars_X_of_ne (by omega) (by omega)
  have t0 : swapVars (R := R) (i + 1) (X i) = X i := swapVars_X_of_ne (by omega) (by omega)
  have t1 : swapVars (R := R) (i + 1) (X (i + 1)) = X (i + 2) := swapVars_X_self (i + 1)
  have t2 : swapVars (R := R) (i + 1) (X (i + 2)) = X (i + 1) := swapVars_X_succ (i + 1)
  set a := divDiff i f with ha
  set b := divDiff (i + 1) a with hb
  set c := divDiff i b with hc
  have h1 := mul_divDiff i f
  have h2 := mul_divDiff (i + 1) a
  have h3 := mul_divDiff i b
  rw [← ha] at h1
  rw [← hb] at h2
  rw [← hc] at h3
  have hsa : swapVars i a = a := swapVars_divDiff i f
  have h5 := congrArg (swapVars (i + 1)) h1
  have h6 := congrArg (swapVars i) h2
  have h7 := congrArg (fun g => swapVars i (swapVars (i + 1) g)) h1
  simp only [map_mul, map_sub, s0, s1, s2, t0, t1, t2, hsa] at h5 h6 h7
  linear_combination (X i - X (i + 2)) * (X (i + 1) - X (i + 2)) * h3 + (X i - X (i + 2)) * h2
    - (X (i + 1) - X (i + 2)) * h6 - h5 + h7 + h1

/-- The Vandermonde product times `∂_{i+1} ∂_i ∂_{i+1} f` is the same alternating sum as in
`vandermonde_mul_divDiff_braid_left`, with the longest permutation written as `t s t`. -/
theorem vandermonde_mul_divDiff_braid_right (i : ℕ) (f : MvPolynomial ℕ R) :
    (X i - X (i + 1)) * (X i - X (i + 2)) * (X (i + 1) - X (i + 2)) *
        divDiff (i + 1) (divDiff i (divDiff (i + 1) f)) =
      f - swapVars i f - swapVars (i + 1) f + swapVars (i + 1) (swapVars i f) +
        swapVars i (swapVars (i + 1) f) -
          swapVars (i + 1) (swapVars i (swapVars (i + 1) f)) := by
  have s0 : swapVars (R := R) i (X i) = X (i + 1) := swapVars_X_self i
  have s1 : swapVars (R := R) i (X (i + 1)) = X i := swapVars_X_succ i
  have s2 : swapVars (R := R) i (X (i + 2)) = X (i + 2) := swapVars_X_of_ne (by omega) (by omega)
  have t0 : swapVars (R := R) (i + 1) (X i) = X i := swapVars_X_of_ne (by omega) (by omega)
  have t1 : swapVars (R := R) (i + 1) (X (i + 1)) = X (i + 2) := swapVars_X_self (i + 1)
  have t2 : swapVars (R := R) (i + 1) (X (i + 2)) = X (i + 1) := swapVars_X_succ (i + 1)
  set a := divDiff (i + 1) f with ha
  set b := divDiff i a with hb
  set c := divDiff (i + 1) b with hc
  have g1 := mul_divDiff (i + 1) f
  have g2 := mul_divDiff i a
  have g3 := mul_divDiff (i + 1) b
  rw [← ha] at g1
  rw [← hb] at g2
  rw [← hc] at g3
  have hta : swapVars (i + 1) a = a := swapVars_divDiff (i + 1) f
  have g4 := congrArg (swapVars (i + 1)) g2
  have g5 := congrArg (swapVars i) g1
  have g6 := congrArg (fun g => swapVars (i + 1) (swapVars i g)) g1
  simp only [map_mul, map_sub, s0, s1, s2, t0, t1, t2, hta] at g4 g5 g6
  simp only [show i + 1 + 1 = i + 2 from rfl] at g1 g3
  linear_combination (X i - X (i + 1)) * (X i - X (i + 2)) * g3 + (X i - X (i + 2)) * g2
    - (X i - X (i + 1)) * g4 - g5 + g6 + g1

/-- The braid relation for adjacent transpositions of variables. -/
theorem swapVars_braid (i : ℕ) (f : MvPolynomial ℕ R) :
    swapVars i (swapVars (i + 1) (swapVars i f)) =
      swapVars (i + 1) (swapVars i (swapVars (i + 1) f)) := by
  have : (swapVars (R := R) i).comp ((swapVars (i + 1)).comp (swapVars i)) =
      (swapVars (i + 1)).comp ((swapVars i).comp (swapVars (i + 1))) := by
    apply MvPolynomial.algHom_ext
    intro k
    have s2 : swapVars (R := R) i (X (i + 2)) = X (i + 2) :=
      swapVars_X_of_ne (by omega) (by omega)
    have t0 : swapVars (R := R) (i + 1) (X i) = X i := swapVars_X_of_ne (by omega) (by omega)
    have t1 : swapVars (R := R) (i + 1) (X (i + 1)) = X (i + 2) := swapVars_X_self (i + 1)
    have t2 : swapVars (R := R) (i + 1) (X (i + 2)) = X (i + 1) := swapVars_X_succ (i + 1)
    rcases (show k = i ∨ k = i + 1 ∨ k = i + 2 ∨ (k ≠ i ∧ k ≠ i + 1 ∧ k ≠ i + 2) by omega)
      with rfl | rfl | rfl | ⟨h0, h1, h2⟩
    · simp only [AlgHom.comp_apply, swapVars_X_self, swapVars_X_succ, s2, t0, t1, t2]
    · simp only [AlgHom.comp_apply, swapVars_X_self, swapVars_X_succ, s2, t0, t1, t2]
    · simp only [AlgHom.comp_apply, swapVars_X_self, swapVars_X_succ, s2, t0, t1, t2]
    · have a1 : swapVars (R := R) i (X k) = X k := swapVars_X_of_ne h0 h1
      have a2 : swapVars (R := R) (i + 1) (X k) = X k := swapVars_X_of_ne h1 h2
      simp only [AlgHom.comp_apply, a1, a2]
  exact congrArg (fun g => g f) this

/-- The braid relation `∂_i ∂_{i+1} ∂_i = ∂_{i+1} ∂_i ∂_{i+1}`, pointwise. -/
theorem divDiff_braid_apply (i : ℕ) (f : MvPolynomial ℕ R) :
    divDiff i (divDiff (i + 1) (divDiff i f)) =
      divDiff (i + 1) (divDiff i (divDiff (i + 1) f)) := by
  have h := (vandermonde_mul_divDiff_braid_left i f).trans
    ((swapVars_braid i f ▸ vandermonde_mul_divDiff_braid_right i f).symm)
  rw [mul_assoc, mul_assoc, mul_assoc, mul_assoc] at h
  have h' := X_sub_X_mul_cancel (by omega) h
  have h'' := X_sub_X_mul_cancel (by omega) h'
  exact X_sub_X_mul_cancel (by omega) h''

/-! ### The nilHecke relations as identities of linear operators -/

/-- Multiplication by `X i`, as an `R`-linear endomorphism of `MvPolynomial ℕ R`. -/
def mulX (i : ℕ) : MvPolynomial ℕ R →ₗ[R] MvPolynomial ℕ R :=
  LinearMap.mulLeft R (X i)

@[simp] theorem mulX_apply (i : ℕ) (f : MvPolynomial ℕ R) : mulX i f = X i * f := rfl

/-- `x_i x_j = x_j x_i`. -/
theorem mulX_comm (i j : ℕ) : mulX (R := R) i ∘ₗ mulX j = mulX j ∘ₗ mulX i :=
  LinearMap.ext fun f => by simp [mul_left_comm]

/-- `x_j ∂_i = ∂_i x_j` for `j ∉ {i, i + 1}`. -/
theorem mulX_divDiff_comm {i j : ℕ} (h : j ≠ i) (h' : j ≠ i + 1) :
    mulX (R := R) j ∘ₗ divDiff i = divDiff i ∘ₗ mulX j :=
  LinearMap.ext fun f => by simp [divDiff_X_mul_of_ne h h']

/-- `∂_i ∂_j = ∂_j ∂_i` for `|i - j| > 1`. -/
theorem divDiff_comm {i j : ℕ} (h : i + 1 < j ∨ j + 1 < i) :
    divDiff (R := R) i ∘ₗ divDiff j = divDiff j ∘ₗ divDiff i :=
  LinearMap.ext (divDiff_comm_apply h)

/-- `∂_i² = 0`. -/
theorem divDiff_divDiff (i : ℕ) : divDiff (R := R) i ∘ₗ divDiff i = 0 :=
  LinearMap.ext (divDiff_divDiff_apply i)

/-- The braid relation `∂_i ∂_{i+1} ∂_i = ∂_{i+1} ∂_i ∂_{i+1}`. -/
theorem divDiff_braid (i : ℕ) :
    divDiff (R := R) i ∘ₗ divDiff (i + 1) ∘ₗ divDiff i =
      divDiff (i + 1) ∘ₗ divDiff i ∘ₗ divDiff (i + 1) :=
  LinearMap.ext (divDiff_braid_apply i)

/-- `x_i ∂_i - ∂_i x_{i+1} = 1`. -/
theorem mulX_divDiff_sub (i : ℕ) :
    mulX (R := R) i ∘ₗ divDiff i - divDiff i ∘ₗ mulX (i + 1) = LinearMap.id :=
  LinearMap.ext fun f => by simp [divDiff_X_succ_mul]

/-- `∂_i x_i - x_{i+1} ∂_i = 1`. -/
theorem divDiff_mulX_sub (i : ℕ) :
    divDiff (R := R) i ∘ₗ mulX i - mulX (i + 1) ∘ₗ divDiff i = LinearMap.id :=
  LinearMap.ext fun f => by simp [divDiff_X_self_mul]

end StringDiagrams.NilHecke
