import StringDiagrams.Examples.NilHecke.DividedDifference
import StringDiagrams.Examples.NilHecke.Relations
import StringDiagrams.Tactic.WordRw

/-!
# Polynomials in the dots and the polynomial slide

The dots `x R n i` on the strands of `n` pairwise commute, so polynomials can be placed on the
strands: `dots R n : MvPolynomial ℕ R →ₐ[R] End (NH.obj R n)` sends `X i` to the dot on strand
`i` (and to `0` if `i ≥ n`). Sliding a polynomial through a crossing produces the divided
difference: for all widths `n`, all positions `i` with `i + 1 < n`, and all polynomials `f`,

* `ψ_mul_dots`: `ψ_i · f = (s_i f) · ψ_i + ∂_i f`;
* `dots_mul_ψ`: `f · ψ_i = ψ_i · (s_i f) + ∂_i f`,

where `s_i = swapVars i` exchanges `X i` and `X (i + 1)`, `∂_i = divDiff i` is the divided
difference operator, and products are composition of operators (`f * g` is `g` followed by
`f`, i.e. `g` drawn below `f`). This is the diagrammatic form of the statement that the nilHecke
algebra acts on polynomials by multiplication and divided differences (KL I, arXiv:0803.4121v2,
§2.2, Example 3, p. 10; indices shifted to start at `0`). For `f = X i` and `f = X (i + 1)`
these are the dot slide relations `ψ_mul_x_sub_x_mul_ψ` and `x_mul_ψ_sub_ψ_mul_x`.

## Main declarations

* `dots R n`, `dots_X`, `dots_C`, `dots_mul_comm`.
* `ψ_mul_x_self`, `ψ_mul_x_succ`, `ψ_mul_x_of_ne`, `ψ_mul_dots_X`: the generator cases, in a
  form suitable for rewriting.
* `ψ_mul_dots`, `dots_mul_ψ`: the polynomial slide in both directions.
* `ψ_mul_dots_of_swap_eq`: `s_i`-invariant polynomials commute with `ψ_i`.
* `ψ_mul_dots_mul_ψ`, `ψ_mul_dots_mul_ψ'`: `ψ_i f ψ_i = (∂_i f) ψ_i = ψ_i (∂_i f)`.
-/

noncomputable section

namespace StringDiagrams.NilHecke

open CategoryTheory MvPolynomial

variable (R : Type*) [CommRing R]

/-! ### Polynomials in the dots -/

/-- The subalgebra of `End (NH.obj R n)` generated by the dots. -/
abbrev dotAlg (n : ℕ) : Subalgebra R (End (NH.obj R n)) :=
  Algebra.adjoin R (Set.range (x R n))

/-- The dots commute, so they generate a commutative subalgebra. -/
instance dotAlg.instCommRing (n : ℕ) : CommRing (dotAlg R n) :=
  Algebra.adjoinCommRingOfComm R (by
    rintro _ ⟨i, rfl⟩ _ ⟨j, rfl⟩
    exact x_mul_x_comm R n i j)

/-- Polynomials in the dots: `X i` is sent to the dot `x R n i` on strand `i`. -/
def dots (n : ℕ) : MvPolynomial ℕ R →ₐ[R] End (NH.obj R n) :=
  (dotAlg R n).val.comp
    (aeval fun i => (⟨x R n i, Algebra.subset_adjoin ⟨i, rfl⟩⟩ : dotAlg R n))

@[simp] theorem dots_X (n i : ℕ) : dots R n (X i) = x R n i := by
  simp [dots]

@[simp] theorem dots_C (n : ℕ) (r : R) : dots R n (C r) = algebraMap R _ r :=
  (dots R n).commutes r

theorem dots_mul_comm (n : ℕ) (f g : MvPolynomial ℕ R) :
    dots R n f * dots R n g = dots R n g * dots R n f := by
  rw [← map_mul, mul_comm, map_mul]

/-! ### The generator cases -/

theorem ψ_mul_x_self {n i : ℕ} (h : i + 1 < n) :
    ψ R n i * x R n i = x R n (i + 1) * ψ R n i + 1 :=
  sub_eq_iff_eq_add'.mp (ψ_mul_x_sub_x_mul_ψ R h)

theorem ψ_mul_x_succ {n i : ℕ} (h : i + 1 < n) :
    ψ R n i * x R n (i + 1) = x R n i * ψ R n i - 1 := by
  rw [← x_mul_ψ_sub_ψ_mul_x R h, sub_sub_cancel]

theorem ψ_mul_x_of_ne {n i j : ℕ} (h : j ≠ i) (h' : j ≠ i + 1) :
    ψ R n i * x R n j = x R n j * ψ R n i :=
  (x_mul_ψ_comm R h h').symm

/-- The polynomial slide for a single variable. -/
theorem ψ_mul_dots_X {n i : ℕ} (h : i + 1 < n) (j : ℕ) :
    ψ R n i * x R n j =
      dots R n (swapVars i (X j)) * ψ R n i + dots R n (divDiff i (X j)) := by
  rcases (show j = i ∨ j = i + 1 ∨ (j ≠ i ∧ j ≠ i + 1) by omega) with rfl | rfl | ⟨h₁, h₂⟩
  · simp [ψ_mul_x_self R h]
  · simp [ψ_mul_x_succ R h, sub_eq_add_neg]
  · simp [swapVars_X_of_ne h₁ h₂, divDiff_X_of_ne h₁ h₂, ψ_mul_x_of_ne R h₁ h₂]

/-! ### The polynomial slide -/

theorem divDiff_swapVars (i : ℕ) (f : MvPolynomial ℕ R) :
    divDiff i (swapVars i f) = -divDiff i f :=
  divDiff_eq_of_mul (by rw [mul_neg, mul_divDiff, swapVars_swapVars, neg_sub])

theorem swapVars_C (i : ℕ) (r : R) : swapVars i (C r : MvPolynomial ℕ R) = C r :=
  (swapVars i).commutes r

/-- Sliding a polynomial up through a crossing: `ψ_i f = (s_i f) ψ_i + ∂_i f`. -/
theorem ψ_mul_dots {n i : ℕ} (h : i + 1 < n) (f : MvPolynomial ℕ R) :
    ψ R n i * dots R n f = dots R n (swapVars i f) * ψ R n i + dots R n (divDiff i f) := by
  induction f using MvPolynomial.induction_on with
  | C r =>
    rw [swapVars_C, divDiff_of_swap_eq (swapVars_C R i r), map_zero, add_zero, dots_C,
      Algebra.commutes]
  | add p q hp hq =>
    simp only [map_add, mul_add, add_mul, hp, hq]
    abel
  | mul_X p j hp =>
    simp only [map_mul, divDiff_mul, map_add, dots_X]
    word_rw [hp, ψ_mul_dots_X R h j]
    abel

/-- Sliding a polynomial down through a crossing: `f ψ_i = ψ_i (s_i f) + ∂_i f`. -/
theorem dots_mul_ψ {n i : ℕ} (h : i + 1 < n) (f : MvPolynomial ℕ R) :
    dots R n f * ψ R n i = ψ R n i * dots R n (swapVars i f) + dots R n (divDiff i f) := by
  rw [ψ_mul_dots R h, swapVars_swapVars, divDiff_swapVars, map_neg]
  abel

/-- Polynomials invariant under `s_i` commute with the crossing `ψ_i`. -/
theorem ψ_mul_dots_of_swap_eq {n i : ℕ} (h : i + 1 < n) {f : MvPolynomial ℕ R}
    (hf : swapVars i f = f) : ψ R n i * dots R n f = dots R n f * ψ R n i := by
  rw [ψ_mul_dots R h, hf, divDiff_of_swap_eq hf, map_zero, add_zero]

/-- `ψ_i f ψ_i = (∂_i f) ψ_i`. -/
theorem ψ_mul_dots_mul_ψ {n i : ℕ} (h : i + 1 < n) (f : MvPolynomial ℕ R) :
    ψ R n i * dots R n f * ψ R n i = dots R n (divDiff i f) * ψ R n i := by
  word_rw [ψ_mul_dots R h, ψ_mul_ψ]

/-- `ψ_i f ψ_i = ψ_i (∂_i f)`. -/
theorem ψ_mul_dots_mul_ψ' {n i : ℕ} (h : i + 1 < n) (f : MvPolynomial ℕ R) :
    ψ R n i * dots R n f * ψ R n i = ψ R n i * dots R n (divDiff i f) := by
  word_rw [dots_mul_ψ R h, ψ_mul_ψ]

end StringDiagrams.NilHecke

end
