import StringDiagrams.Examples.OddTemperleyLieb.KZeroIso

/-!
# `K₀(SKar(STL(δ)))` is a polynomial algebra (Example 1.17(iii))

J. Brundan, A. P. Ellis, *Monoidal supercategories*, arXiv:1603.05928v3, Example 1.17(iii),
last sentence: `K₀(SKar(STL(δ)))` is a polynomial algebra over `Zπ` generated by `[2]_{x,π}`,
the class of the generating object.

* In `Zπ[x, x⁻¹]`, the `Zπ`-algebra map `Zπ[X] → Zπ[x, x⁻¹]`, `X ↦ [2]_{x,π} = x + π x⁻¹`, is
  injective (`aeval_brk_two_injective`: `[2]^j` has top term `x^j`), and its image is the image
  of `K₀` (`range_aeval_brk_two`: by `[n+1][2] = [n+2] + π[n]`, every `[n+1]_{x,π}` is a
  polynomial in `[2]_{x,π}`).
* **Example 1.17(iii).** `K₀Poly : K₀(SKar(STL(δ))) ≃ₐ[Zπ] Zπ[X]` sends the class of the
  generating object `P 1 0 = (f_1)^0_0` to `X` (`K₀Poly_classJw_one_zero`).
-/

noncomputable section

namespace StringDiagrams.OddTemperleyLieb

open CategoryTheory
open Rep (delta)
open LaurentPolynomial (T C single_eq_C_mul_T)

/-! ## `[2]_{x,π}` generates a polynomial algebra -/

theorem brk_two : brk 2 = T 1 + πL * T (-1) := by
  rw [brk_succ]
  simp [Finset.sum_range_succ]

theorem mul_brk_two_apply (f : LZ) (i : ℤ) :
    (f * brk 2) i = f (i - 1) + f (i + 1) * Zπ.π := by
  rw [brk_two, mul_add, Finsupp.add_apply, ← single_eq_C_mul_T, LaurentPolynomial.T,
    AddMonoidAlgebra.mul_single_apply, AddMonoidAlgebra.mul_single_apply, mul_one, sub_neg_eq_add]

/-- `[2]_{x,π}^j = x^j + (lower terms)`. -/
theorem brk_two_pow_apply (j : ℕ) :
    (brk 2 ^ j) j = 1 ∧ ∀ i : ℤ, (j : ℤ) < i → (brk 2 ^ j) i = 0 := by
  induction j with
  | zero =>
    refine ⟨?_, fun i hi => ?_⟩
    · rw [pow_zero, ← LaurentPolynomial.T_zero, LaurentPolynomial.T, Finsupp.single_apply,
        if_pos (by simp)]
    · rw [pow_zero, ← LaurentPolynomial.T_zero, LaurentPolynomial.T, Finsupp.single_apply,
        if_neg (by omega)]
  | succ j ih =>
    refine ⟨?_, fun i hi => ?_⟩
    · rw [pow_succ (brk 2) j, mul_brk_two_apply]
      push_cast
      rw [add_sub_cancel_right, ih.1, ih.2 _ (by omega)]; simp
    · rw [pow_succ (brk 2) j, mul_brk_two_apply, ih.2 _ (by omega), ih.2 _ (by omega)]; simp

/-- `X ↦ [2]_{x,π}` is injective on `Zπ[X]`. -/
theorem aeval_brk_two_injective : Function.Injective (Polynomial.aeval (R := Zπ) (brk 2)) := by
  rw [injective_iff_map_eq_zero]
  intro p hp
  by_contra hne
  have h := congrArg (fun f : LZ => f (p.natDegree : ℤ)) hp
  simp only [Polynomial.aeval_eq_sum_range] at h
  rw [Finset.sum_apply', Finset.sum_eq_single p.natDegree] at h
  · rw [Finsupp.smul_apply, (brk_two_pow_apply _).1, smul_eq_mul, mul_one] at h
    exact hne (Polynomial.leadingCoeff_eq_zero.mp h)
  · intro i hi hne'
    rw [Finsupp.smul_apply, (brk_two_pow_apply i).2 _ (by simp at hi; omega), smul_zero]
  · simp

theorem πL_mem_range : πL ∈ (Polynomial.aeval (R := Zπ) (brk 2)).range := by
  rw [πL, LaurentPolynomial.C_eq_algebraMap]
  exact Subalgebra.algebraMap_mem _ _

theorem brk_mem_range (n : ℕ) : brk n ∈ (Polynomial.aeval (R := Zπ) (brk 2)).range := by
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    match n with
    | 0 => change qbracket xU πL 0 ∈ _; rw [qbracket_zero]; exact Subalgebra.zero_mem _
    | 1 => change qbracket xU πL 1 ∈ _; rw [qbracket_one]; exact Subalgebra.one_mem _
    | n + 2 =>
      have e : brk (n + 2) = brk (n + 1) * brk 2 - πL * brk n := by
        change qbracket xU πL (n + 2) = qbracket xU πL (n + 1) * qbracket xU πL 2 - πL * qbracket xU πL n
        rw [qbracket_succ_mul_two]; ring
      rw [e]
      exact Subalgebra.sub_mem _ (Subalgebra.mul_mem _ (ih _ (by omega)) ⟨Polynomial.X, by simp⟩)
        (Subalgebra.mul_mem _ πL_mem_range (ih _ (by omega)))

theorem genL_mem_range (x : ℕ × ZMod 2) : genL x ∈ (Polynomial.aeval (R := Zπ) (brk 2)).range :=
  Subalgebra.mul_mem _ (Subalgebra.pow_mem _ πL_mem_range _) (brk_mem_range _)

variable {k : Type*} [Field k] (q : kˣ)

local notation "δq" => delta q

variable (hq : ∀ n : ℕ, 0 < n → q ^ n ≠ 1)
include hq

omit hq in
theorem algebraMap_eq (c : Zπ) :
    algebraMap Zπ (K₀ (SKar k (STL k δq))) c = c • (1 : K₀ (SKar k (STL k δq))) :=
  (Algebra.smul_def c 1).trans (mul_one _) |>.symm

theorem K₀ToLZ_algebraMap (c : Zπ) :
    K₀ToLZ q hq (algebraMap Zπ (K₀ (SKar k (STL k δq))) c) = C c := by
  obtain ⟨a, b, rfl⟩ := Zπ.exists_eq_add_mul_π c
  rw [algebraMap_eq, add_smul, mul_smul, map_add, Int.cast_smul_eq_zsmul, Int.cast_smul_eq_zsmul,
    map_zsmul, map_zsmul]
  change a • K₀ToLZlin q hq 1 + b • K₀ToLZlin q hq (Zπ.π • 1) = _
  rw [K₀ToLZlin_π_smul]
  change a • K₀ToLZ q hq 1 + b • (πL * K₀ToLZ q hq 1) = _
  rw [map_one, mul_one, map_add, map_mul, map_intCast, map_intCast, zsmul_eq_mul, zsmul_eq_mul,
    mul_one]

/-- The image of `K₀` in `Zπ[x, x⁻¹]` is the `Zπ`-subalgebra generated by `[2]_{x,π}`. -/
theorem range_aeval_brk_two :
    (K₀ToLZ q hq).range = (Polynomial.aeval (R := Zπ) (brk 2)).range.toSubring := by
  ext f
  constructor
  · rintro ⟨x, rfl⟩
    change K₀ToLZ q hq x ∈ (Polynomial.aeval (R := Zπ) (brk 2)).range
    have hx : x ∈ Submodule.span ℤ (Set.range (classJw q hq)) := by
      rw [span_classJw]; trivial
    induction hx using Submodule.span_induction with
    | mem y hy =>
      obtain ⟨z, rfl⟩ := hy
      rw [K₀ToLZ_classJw]; exact genL_mem_range z
    | zero => rw [map_zero]; exact Subalgebra.zero_mem _
    | add y z _ _ hy hz => rw [map_add]; exact Subalgebra.add_mem _ hy hz
    | smul a y _ hy => rw [map_zsmul]; exact Subalgebra.zsmul_mem _ hy a
  · rintro ⟨p, rfl⟩
    show Polynomial.aeval (R := Zπ) (brk 2) p ∈ (K₀ToLZ q hq).range
    induction p using Polynomial.induction_on with
    | C c => exact ⟨algebraMap Zπ _ c, by rw [K₀ToLZ_algebraMap, Polynomial.aeval_C,
        LaurentPolynomial.C_eq_algebraMap]⟩
    | add p p' hp hp' => rw [map_add]; exact Subring.add_mem _ hp hp'
    | monomial n c _ =>
      rw [map_mul, map_pow, Polynomial.aeval_X, Polynomial.aeval_C]
      refine Subring.mul_mem _ (RingHom.mem_range.mpr ⟨algebraMap Zπ _ c, ?_⟩)
        (Subring.pow_mem _ (RingHom.mem_range.mpr ⟨classJw q hq (1, 0), ?_⟩) _)
      · rw [K₀ToLZ_algebraMap, LaurentPolynomial.C_eq_algebraMap]
      · rw [K₀ToLZ_classJw]; simp [genL]

/-- The ring isomorphism `K₀(SKar(STL(δ))) ≅ Zπ[X]` through `Zπ[x, x⁻¹]`. -/
def K₀PolyRing : K₀ (SKar k (STL k δq)) ≃+* Polynomial Zπ :=
  (K₀Equiv q hq).trans ((RingEquiv.subringCongr (range_aeval_brk_two q hq)).trans
    (AlgEquiv.ofInjective _ aeval_brk_two_injective).symm.toRingEquiv)

theorem aeval_K₀PolyRing (x : K₀ (SKar k (STL k δq))) :
    Polynomial.aeval (brk 2) (K₀PolyRing q hq x) = K₀ToLZ q hq x := by
  let e3 := AlgEquiv.ofInjective (Polynomial.aeval (R := Zπ) (brk 2)) aeval_brk_two_injective
  let y : (Polynomial.aeval (R := Zπ) (brk 2)).range :=
    (RingEquiv.subringCongr (range_aeval_brk_two q hq)) ((K₀ToLZ q hq).rangeRestrict x)
  change Polynomial.aeval (brk 2) (e3.symm y) = _
  rw [← AlgEquiv.ofInjective_apply _ aeval_brk_two_injective]
  change ((e3 (e3.symm y) : (Polynomial.aeval (R := Zπ) (brk 2)).range) : LZ) = _
  rw [AlgEquiv.apply_symm_apply]
  rfl

/-- **Example 1.17(iii).** `K₀(SKar(STL(δ)))` is a polynomial algebra over `Zπ`, generated by the
class of the generating object: the isomorphism `K₀ ≅ Zπ[X]` of `Zπ`-algebras sends `[P 1 0]` to
`X` (`K₀Poly_classJw_one_zero`). -/
def K₀Poly : K₀ (SKar k (STL k δq)) ≃ₐ[Zπ] Polynomial Zπ :=
  AlgEquiv.ofRingEquiv (f := K₀PolyRing q hq) fun c => by
    apply aeval_brk_two_injective
    rw [aeval_K₀PolyRing, K₀ToLZ_algebraMap, Polynomial.algebraMap_apply, Algebra.id.map_eq_id,
      RingHom.id_apply, Polynomial.aeval_C, LaurentPolynomial.C_eq_algebraMap]

theorem K₀Poly_apply (x : K₀ (SKar k (STL k δq))) : K₀Poly q hq x = K₀PolyRing q hq x := rfl

/-- The class of the generating object `P 1 0 = (f_1)^0_0` corresponds to `X`. -/
theorem K₀Poly_classJw_one_zero : K₀Poly q hq (classJw q hq (1, 0)) = Polynomial.X := by
  apply aeval_brk_two_injective
  rw [K₀Poly_apply, aeval_K₀PolyRing, K₀ToLZ_classJw, Polynomial.aeval_X]
  simp [genL]

/-- The class of `P 1 0` is the class of the generating object `1` of `STL(δ)`, viewed in
`SKar(STL(δ))`; its image in `Zπ[x, x⁻¹]` is `[2]_{x,π}`. -/
theorem K₀ToLZ_classJw_one_zero : K₀ToLZ q hq (classJw q hq (1, 0)) = brk 2 := by
  rw [K₀ToLZ_classJw]; simp [genL]

end StringDiagrams.OddTemperleyLieb

end
