import StringDiagrams.Presentation

/-!
# Generation of presented categories by layers

Every morphism of a presented category is an `R`-linear combination of classes of diagrams
(`Presentation.hom_induction`), and every diagram is a composite of single layers
(`Diagram.eq_layer_comp`, `Presentation.diag_induction`). Consequently a property of
morphisms that holds for identities (retyped along equalities of objects) and single layers
and is stable under composition, sums and scalar multiples holds for all morphisms
(`Presentation.hom_induction_layers`).

For a set of objects `C` closed under layers, morphisms from `C` to its complement vanish
(`Presentation.eq_zero_of_mem_of_not_mem`, `Presentation.eq_zero_of_invariant`) and morphisms
within `C` are generated by identities and single layers (`Presentation.mem_of_layers`; for
endomorphism algebras, `Presentation.mem_subalgebra_of_layers` in
`StringDiagrams.Transport`). Linear maps on Hom modules are determined by their values on
classes of diagrams (`Presentation.linearMap_ext_diag`).
-/

noncomputable section

namespace StringDiagrams

open CategoryTheory

universe w v u₀ u₁ u₂

variable {S : Signature.{u₀, u₁, u₂}}

namespace Diagram

variable {a b : Obj S}

/-- A diagram with at least one layer is its first layer followed by the rest. -/
theorem eq_layer_comp {L : Layer S} {ls : List (Layer S)} (h : Chain a (L :: ls) b) :
    mk (L :: ls) h = layer L h.1 h.2.1 rfl ≫ mk ls h.2.2 := by
  ext; simp

/-- The empty diagram is an identity, retyped. -/
theorem mk_nil (h : Chain a [] b) : mk [] h = eqToHom h := by
  ext; simp

end Diagram

namespace Presentation

variable {R : Type w} [CommRing R] (P : Presentation.{w, v} S R)

/-- Induction on morphisms of the presented category: classes of diagrams, sums, scalar
multiples. -/
theorem hom_induction {a b : Obj S} {p : (P.obj a ⟶ P.obj b) → Prop}
    (diag : ∀ d : a ⟶ b, p (P.diag d)) (zero : p 0) (add : ∀ f g, p f → p g → p (f + g))
    (smul : ∀ (r : R) f, p f → p (r • f)) (f : P.obj a ⟶ P.obj b) : p f := by
  obtain ⟨f, rfl⟩ := P.linFunctor.map_surjective f
  change p (P.lin f)
  induction f using Finsupp.induction_linear with
  | zero => rw [lin_zero]; exact zero
  | add f g hf hg => rw [lin_add]; exact add _ _ hf hg
  | single d r => rw [lin_single]; exact smul r _ (diag d)

/-- Induction on diagrams: retyped identities, and a layer followed by a diagram. -/
theorem diag_induction {p : ∀ {a b : Obj S}, (P.obj a ⟶ P.obj b) → Prop}
    (nil : ∀ {a b : Obj S} (h : a = b), p (P.diag (eqToHom h)))
    (cons : ∀ {b : Obj S} (L : Layer S) (hv : L.Valid) (d : L.cod ⟶ b),
      p (P.diag d) → p (P.diag (Diagram.ofLayer L hv ≫ d)))
    {a b : Obj S} (d : a ⟶ b) : p (P.diag d) := by
  obtain ⟨ls, h⟩ := d
  induction ls generalizing a with
  | nil =>
    have e : (⟨[], h⟩ : a ⟶ b) = eqToHom h := Diagram.mk_nil h
    rw [e]; exact nil h
  | cons L ls ih =>
    obtain ⟨hv, rfl, hc⟩ := h
    exact cons L hv _ (ih hc)

/-- Induction on morphisms of the presented category via layers. -/
theorem hom_induction_layers {p : ∀ {a b : Obj S}, (P.obj a ⟶ P.obj b) → Prop}
    (nil : ∀ {a b : Obj S} (h : a = b), p (P.diag (eqToHom h)))
    (layer : ∀ (L : Layer S) (hv : L.Valid), p (P.diag (Diagram.ofLayer L hv)))
    (comp : ∀ {a b c : Obj S} (f : P.obj a ⟶ P.obj b) (g : P.obj b ⟶ P.obj c),
      p f → p g → p (f ≫ g))
    (zero : ∀ {a b : Obj S}, p (0 : P.obj a ⟶ P.obj b))
    (add : ∀ {a b : Obj S} (f g : P.obj a ⟶ P.obj b), p f → p g → p (f + g))
    (smul : ∀ {a b : Obj S} (r : R) (f : P.obj a ⟶ P.obj b), p f → p (r • f))
    {a b : Obj S} (f : P.obj a ⟶ P.obj b) : p f :=
  P.hom_induction (p := p)
    (P.diag_induction (p := p) nil fun L hv d hd => by
      rw [diag_comp]; exact comp _ _ (layer L hv) hd)
    zero add smul f

/-- `R`-linear maps out of a Hom module of the presented category agree if they agree on
classes of diagrams. -/
theorem linearMap_ext_diag {a b : Obj S} {M : Type*} [AddCommGroup M] [Module R M]
    {φ ψ : (P.obj a ⟶ P.obj b) →ₗ[R] M} (h : ∀ d : a ⟶ b, φ (P.diag d) = ψ (P.diag d)) :
    φ = ψ := by
  ext f
  induction f using P.hom_induction with
  | diag d => exact h d
  | zero => simp
  | add f g hf hg => rw [map_add, map_add, hf, hg]
  | smul r f hf => rw [map_smul, map_smul, hf]

/-! ### Sets of objects closed under layers

Let `C` be a set of objects such that every layer with source in `C` has target in `C` (for
instance, the objects of a given width, when every generator preserves the width). Then every
morphism out of an object of `C` into an object outside `C` vanishes, and the morphisms between
objects of `C` are generated by identities and single layers. -/

section Closed

variable (C : Set (Obj S)) (hC : ∀ (L : Layer S), L.Valid → L.dom ∈ C → L.cod ∈ C)
include hC

/-- Joint statement of `eq_zero_of_mem_of_not_mem` and `mem_of_layers`. -/
private theorem closed_aux (M : ∀ a b : Obj S, Submodule R (P.obj a ⟶ P.obj b))
    (hid : ∀ a ∈ C, 𝟙 (P.obj a) ∈ M a a)
    (hcomp : ∀ {a b c : Obj S}, a ∈ C → b ∈ C → c ∈ C → ∀ (f : P.obj a ⟶ P.obj b)
      (g : P.obj b ⟶ P.obj c), f ∈ M a b → g ∈ M b c → f ≫ g ∈ M a c)
    (hlayer : ∀ (L : Layer S) (hv : L.Valid), L.dom ∈ C →
      P.diag (Diagram.ofLayer L hv) ∈ M L.dom L.cod)
    {a b : Obj S} (f : P.obj a ⟶ P.obj b) :
    a ∈ C → (b ∈ C → f ∈ M a b) ∧ (b ∉ C → f = 0) := by
  induction f using P.hom_induction_layers with
  | nil h =>
    subst h
    intro ha
    exact ⟨fun _ => by simpa using hid _ ha, fun hb => absurd ha hb⟩
  | layer L hv =>
    intro ha
    exact ⟨fun _ => hlayer L hv ha, fun hb => absurd (hC L hv ha) hb⟩
  | comp f g hf hg =>
    rename_i a b c
    intro ha
    by_cases hb : b ∈ C
    · refine ⟨fun hc => hcomp ha hb hc f g ((hf ha).1 hb) ((hg hb).1 hc), fun hc => ?_⟩
      rw [(hg hb).2 hc, Limits.comp_zero]
    · have hf0 : f = 0 := (hf ha).2 hb
      subst hf0
      exact ⟨fun _ => by rw [Limits.zero_comp]; exact Submodule.zero_mem _,
        fun _ => Limits.zero_comp⟩
  | zero => exact fun _ => ⟨fun _ => Submodule.zero_mem _, fun _ => rfl⟩
  | add f g hf hg =>
    intro ha
    exact ⟨fun hb => Submodule.add_mem _ ((hf ha).1 hb) ((hg ha).1 hb),
      fun hb => by rw [(hf ha).2 hb, (hg ha).2 hb, add_zero]⟩
  | smul r f hf =>
    intro ha
    exact ⟨fun hb => Submodule.smul_mem _ r ((hf ha).1 hb), fun hb => by rw [(hf ha).2 hb, smul_zero]⟩

/-- If every layer with source in `C` has target in `C`, then every morphism from an object of
`C` to an object outside `C` vanishes. -/
theorem eq_zero_of_mem_of_not_mem {a b : Obj S} (ha : a ∈ C) (hb : b ∉ C)
    (f : P.obj a ⟶ P.obj b) : f = 0 :=
  (P.closed_aux C hC (fun _ _ => ⊤) (fun _ _ => trivial) (fun _ _ _ _ _ _ _ => trivial)
    (fun _ _ _ => trivial) f ha).2 hb

/-- **Generation by layers.** If every layer with source in `C` has target in `C`, then every
morphism between objects of `C` lies in any family of submodules that contains the
identities and the single layers with source in `C` and is closed under composition. -/
theorem mem_of_layers (M : ∀ a b : Obj S, Submodule R (P.obj a ⟶ P.obj b))
    (hid : ∀ a ∈ C, 𝟙 (P.obj a) ∈ M a a)
    (hcomp : ∀ {a b c : Obj S}, a ∈ C → b ∈ C → c ∈ C → ∀ (f : P.obj a ⟶ P.obj b)
      (g : P.obj b ⟶ P.obj c), f ∈ M a b → g ∈ M b c → f ≫ g ∈ M a c)
    (hlayer : ∀ (L : Layer S) (hv : L.Valid), L.dom ∈ C →
      P.diag (Diagram.ofLayer L hv) ∈ M L.dom L.cod)
    {a b : Obj S} (ha : a ∈ C) (hb : b ∈ C) (f : P.obj a ⟶ P.obj b) : f ∈ M a b :=
  (P.closed_aux C hC M hid hcomp hlayer f ha).1 hb

end Closed

/-- If a function `κ` on objects is preserved by every layer (for instance the number of
strands, when every generator preserves it), then morphisms between objects with different
values of `κ` vanish. -/
theorem eq_zero_of_invariant {ι : Type*} (κ : Obj S → ι)
    (hκ : ∀ (L : Layer S), L.Valid → κ L.cod = κ L.dom) {a b : Obj S} (h : κ a ≠ κ b)
    (f : P.obj a ⟶ P.obj b) : f = 0 :=
  P.eq_zero_of_mem_of_not_mem {x | κ x = κ a} (fun L hv hL => (hκ L hv).trans hL) rfl
    (fun hb => h hb.symm) f

end Presentation

end StringDiagrams

end
