import StringDiagrams.Syntax
import Mathlib.Algebra.Category.ModuleCat.Adjunctions
import Mathlib.CategoryTheory.Quotient.Linear
import Mathlib.CategoryTheory.Quotient.Preadditive

/-!
# Presented linear 2-categories

Given a signature `S` and a commutative ring `R`, a `Presentation S R` is a family of
relations, each an `R`-linear combination of diagrams `rel i : a ⟶ b` in the free
`R`-linear 2-category (`LinDiagram R a b`, Mathlib's `Free R (Obj S)`), read as `rel i = 0`.

The presented category `P.Presented` is the quotient of the free `R`-linear 2-category by
the two-sided *tensor ideal* generated by

* the relations `P.rel i`, and
* the (super) interchange law: for generators `g`, `h` and a word `w`, the diagram with
  `g` below `h` on the object `dom g ⊗ w ⊗ dom h` equals `(-1)^{|g||h|}` times the diagram
  with `h` below `g` (`InterchangeData`),

where "tensor ideal" means closure under whiskering by arbitrary (compatible) objects on
the left and right and under composition on either side. It is an `R`-linear category;
its morphisms are the diagrams of the presentation modulo the relations.

## Main definitions and results

* `StringDiagrams.Presentation`, `Presentation.Presented`, `Presentation.obj`.
* `Presentation.lin`: the quotient functor from linear combinations of diagrams, and
  `Presentation.layer`: the class of a single layer.
* `Presentation.lin_rel`: every whiskered relation holds in the presented category;
  `Presentation.lin_interchange`: likewise for the interchange law.
* `Presentation.lift` / `Presentation.lift_diag` (soundness): a functor from the free
  2-category to any `R`-linear category that kills every whiskered relation and every
  whiskered interchange relation factors through the presented category.
* `Interpretation`: the functor determined by images of layers
  (`Interpretation.functor`), with `Interpretation.map_mk_cons` computing it on diagrams.
-/

noncomputable section

namespace StringDiagrams

open CategoryTheory

universe w v u₀ u₁ u₂

variable {S : Signature.{u₀, u₁, u₂}}

section LinDiagram

variable (R : Type w) [CommRing R]

/-- `R`-linear combinations of diagrams from `a` to `b`: morphisms of the free `R`-linear
2-category on `S`. -/
abbrev LinDiagram (a b : Obj S) : Type _ := Free.of R a ⟶ Free.of R b

variable {R}

namespace LinDiagram

variable {a b c : Obj S}

/-- A single diagram with coefficient `1`. -/
abbrev of (f : a ⟶ b) : LinDiagram R a b := Finsupp.single f 1

theorem of_comp (f : a ⟶ b) (g : b ⟶ c) : (of (f ≫ g) : LinDiagram R a c) = of f ≫ of g := by
  have := Free.single_comp_single R (Obj S) f g (1 : R) 1
  rw [one_mul] at this
  exact this.symm

/-- Whiskering of linear combinations of diagrams. -/
def whisker (f : LinDiagram R a b) (u : Obj S) (v : List S.Colour)
    (hw : a.WhiskerOK u v) : LinDiagram R (a.whisker u v) (b.whisker u v) :=
  Finsupp.mapDomain (fun d => Diagram.whisker d u v hw) f

@[simp] theorem whisker_single (f : a ⟶ b) (r : R) (u : Obj S) (v : List S.Colour)
    (hw : a.WhiskerOK u v) :
    whisker (Finsupp.single f r : LinDiagram R a b) u v hw =
      Finsupp.single (Diagram.whisker f u v hw) r :=
  Finsupp.mapDomain_single

@[simp] theorem whisker_of (f : a ⟶ b) (u : Obj S) (v : List S.Colour) (hw : a.WhiskerOK u v) :
    whisker (of f : LinDiagram R a b) u v hw = of (Diagram.whisker f u v hw) :=
  Finsupp.mapDomain_single

theorem whisker_sub (f g : LinDiagram R a b) (u : Obj S) (v : List S.Colour)
    (hw : a.WhiskerOK u v) : whisker (f - g) u v hw = whisker f u v hw - whisker g u v hw :=
  (Finsupp.lmapDomain R R _).map_sub f g

theorem whisker_neg (f : LinDiagram R a b) (u : Obj S) (v : List S.Colour)
    (hw : a.WhiskerOK u v) : whisker (-f) u v hw = -whisker f u v hw :=
  (Finsupp.lmapDomain R R _).map_neg f

theorem whisker_add (f g : LinDiagram R a b) (u : Obj S) (v : List S.Colour)
    (hw : a.WhiskerOK u v) : whisker (f + g) u v hw = whisker f u v hw + whisker g u v hw :=
  Finsupp.mapDomain_add

theorem whisker_smul (r : R) (f : LinDiagram R a b) (u : Obj S) (v : List S.Colour)
    (hw : a.WhiskerOK u v) : whisker (r • f) u v hw = r • whisker f u v hw :=
  Finsupp.mapDomain_smul _ _

/-- Retype a linear combination of diagrams along equalities of its boundary objects. -/
def cast {a' b' : Obj S} (f : LinDiagram R a b) (ha : a = a') (hb : b = b') :
    LinDiagram R a' b' :=
  Finsupp.mapDomain (fun d => Diagram.cast d ha hb) f

@[simp] theorem cast_single {a' b' : Obj S} (f : a ⟶ b) (r : R) (ha : a = a') (hb : b = b') :
    cast (Finsupp.single f r : LinDiagram R a b) ha hb = Finsupp.single (Diagram.cast f ha hb) r :=
  Finsupp.mapDomain_single

@[simp] theorem cast_of {a' b' : Obj S} (f : a ⟶ b) (ha : a = a') (hb : b = b') :
    cast (of f : LinDiagram R a b) ha hb = of (Diagram.cast f ha hb) :=
  Finsupp.mapDomain_single

@[simp] theorem cast_add {a' b' : Obj S} (f g : LinDiagram R a b) (ha : a = a') (hb : b = b') :
    cast (f + g) ha hb = cast f ha hb + cast g ha hb :=
  Finsupp.mapDomain_add

@[simp] theorem cast_sub {a' b' : Obj S} (f g : LinDiagram R a b) (ha : a = a') (hb : b = b') :
    cast (f - g) ha hb = cast f ha hb - cast g ha hb :=
  (Finsupp.lmapDomain R R _).map_sub f g

@[simp] theorem cast_neg {a' b' : Obj S} (f : LinDiagram R a b) (ha : a = a') (hb : b = b') :
    cast (-f) ha hb = -cast f ha hb :=
  (Finsupp.lmapDomain R R _).map_neg f

@[simp] theorem cast_smul {a' b' : Obj S} (r : R) (f : LinDiagram R a b) (ha : a = a')
    (hb : b = b') : cast (r • f) ha hb = r • cast f ha hb :=
  Finsupp.mapDomain_smul _ _

@[simp] theorem cast_rfl (f : LinDiagram R a b) : cast f rfl rfl = f := by
  simp only [cast, Diagram.cast_rfl]; exact Finsupp.mapDomain_id

end LinDiagram

end LinDiagram

/-! ## The interchange law -/

/-- Data for one instance of the interchange law: generators `g` (left) and `h` (right)
separated by the identity on the word `mid`, starting in region `start`. -/
structure InterchangeData (S : Signature.{u₀, u₁, u₂}) where
  /-- The leftmost region. -/
  start : S.Region
  /-- The left generator. -/
  g : S.Gen
  /-- The strands between the two generators. -/
  mid : List S.Colour
  /-- The right generator. -/
  h : S.Gen

namespace InterchangeData

variable (x : InterchangeData S)

/-- Bottom boundary `dom g ⊗ mid ⊗ dom h`. -/
def dom : Obj S := ⟨x.start, S.dom x.g ++ x.mid ++ S.dom x.h⟩

/-- Top boundary `cod g ⊗ mid ⊗ cod h`. -/
def cod : Obj S := ⟨x.start, S.cod x.g ++ x.mid ++ S.cod x.h⟩

/-- `g` first: bottom layer. -/
def gh₁ : Layer S := ⟨x.start, [], x.g, x.mid ++ S.dom x.h⟩
/-- `g` first: top layer. -/
def gh₂ : Layer S := ⟨x.start, S.cod x.g ++ x.mid, x.h, []⟩
/-- `h` first: bottom layer. -/
def hg₁ : Layer S := ⟨x.start, S.dom x.g ++ x.mid, x.h, []⟩
/-- `h` first: top layer. -/
def hg₂ : Layer S := ⟨x.start, [], x.g, x.mid ++ S.cod x.h⟩

/-- The four layers involved are well formed. -/
structure Valid : Prop where
  gh₁ : x.gh₁.Valid
  gh₂ : x.gh₂.Valid
  hg₁ : x.hg₁.Valid
  hg₂ : x.hg₂.Valid

theorem valid_of_subsingleton [Subsingleton S.Region] : x.Valid :=
  ⟨Layer.valid_of_subsingleton _, Layer.valid_of_subsingleton _,
    Layer.valid_of_subsingleton _, Layer.valid_of_subsingleton _⟩

/-- The Koszul sign `(-1)^{|g||h|}`. -/
def sign : ℤ := if S.odd x.g && S.odd x.h then -1 else 1

variable {x}

/-- The diagram with `g` below `h`. -/
def ghDiagram (hx : x.Valid) : x.dom ⟶ x.cod :=
  Diagram.mk [x.gh₁, x.gh₂]
    ⟨hx.gh₁, by simp [gh₁, dom, Layer.dom],
      hx.gh₂, by simp [gh₁, gh₂, Layer.dom, Layer.cod], by simp [gh₂, cod, Layer.cod]⟩

/-- The diagram with `h` below `g`. -/
def hgDiagram (hx : x.Valid) : x.dom ⟶ x.cod :=
  Diagram.mk [x.hg₁, x.hg₂]
    ⟨hx.hg₁, by simp [hg₁, dom, Layer.dom],
      hx.hg₂, by simp [hg₁, hg₂, Layer.dom, Layer.cod], by simp [hg₂, cod, Layer.cod]⟩

/-- The interchange relation `(g below h) - (-1)^{|g||h|} (h below g)`. -/
def rel (R : Type w) [CommRing R] (hx : x.Valid) : LinDiagram R x.dom x.cod :=
  LinDiagram.of (ghDiagram hx) - ((x.sign : ℤ) : R) • LinDiagram.of (hgDiagram hx)

end InterchangeData

/-! ## Presentations -/

/-- A presentation of an `R`-linear 2-category on the signature `S`: a family of relations
`rel i = 0` between linear combinations of diagrams. The interchange law is always imposed
in addition (see `Presentation.Presented`). -/
structure Presentation (S : Signature.{u₀, u₁, u₂}) (R : Type w) [CommRing R] where
  /-- Index type of the relations. -/
  Rel : Type v
  /-- Bottom boundary of a relation. -/
  dom : Rel → Obj S
  /-- Top boundary of a relation. -/
  cod : Rel → Obj S
  /-- The relation `rel i = 0`. -/
  rel : (i : Rel) → LinDiagram R (dom i) (cod i)

namespace Presentation

variable {R : Type w} [CommRing R] (P : Presentation.{w, v} S R)

/-- All relations imposed in `P.Presented`: those of `P` and the interchange law. -/
inductive AllRel (P : Presentation.{w, v} S R) : Type (max v u₀ u₁ u₂)
  | user (i : P.Rel)
  | interchange (x : InterchangeData S) (hx : x.Valid)

/-- Bottom boundary of an imposed relation. -/
def AllRel.dom {P : Presentation.{w, v} S R} : P.AllRel → Obj S
  | .user i => P.dom i
  | .interchange x _ => x.dom

/-- Top boundary of an imposed relation. -/
def AllRel.cod {P : Presentation.{w, v} S R} : P.AllRel → Obj S
  | .user i => P.cod i
  | .interchange x _ => x.cod

/-- The imposed relation itself. -/
def AllRel.rel {P : Presentation.{w, v} S R} :
    (k : P.AllRel) → LinDiagram R k.dom k.cod
  | .user i => P.rel i
  | .interchange _ hx => InterchangeData.rel R hx

/-- Generators of the tensor ideal: whiskered relations composed on both sides. -/
inductive IdealGen : ∀ {a b : Obj S}, LinDiagram R a b → Prop
  | intro (k : P.AllRel) (u : Obj S) (v : List S.Colour) (hw : k.dom.WhiskerOK u v)
      {a b : Obj S} (pre : LinDiagram R a (k.dom.whisker u v))
      (post : LinDiagram R (k.cod.whisker u v) b) :
      IdealGen (pre ≫ LinDiagram.whisker k.rel u v hw ≫ post)

/-- The tensor ideal generated by the relations and the interchange law. -/
def ideal (a b : Obj S) : Submodule R (LinDiagram R a b) :=
  Submodule.span R {f | P.IdealGen f}

theorem comp_mem_ideal {a b c : Obj S} (g : LinDiagram R a b) {f : LinDiagram R b c}
    (hf : f ∈ P.ideal b c) : g ≫ f ∈ P.ideal a c := by
  induction hf using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨k, u, v, hw, pre, post⟩ := hx
    apply Submodule.subset_span
    rw [← Category.assoc]
    exact IdealGen.intro k u v hw _ post
  | zero => simp
  | add x y _ _ hx hy => rw [Preadditive.comp_add]; exact Submodule.add_mem _ hx hy
  | smul r x _ hx => rw [Linear.comp_smul]; exact Submodule.smul_mem _ r hx

theorem mem_ideal_comp {a b c : Obj S} {f : LinDiagram R a b} (hf : f ∈ P.ideal a b)
    (g : LinDiagram R b c) : f ≫ g ∈ P.ideal a c := by
  induction hf using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨k, u, v, hw, pre, post⟩ := hx
    apply Submodule.subset_span
    simp only [Category.assoc]
    exact IdealGen.intro k u v hw pre _
  | zero => simp
  | add x y _ _ hx hy => rw [Preadditive.add_comp]; exact Submodule.add_mem _ hx hy
  | smul r x _ hx => rw [Linear.smul_comp]; exact Submodule.smul_mem _ r hx

theorem whisker_rel_mem_ideal (k : P.AllRel) (u : Obj S) (v : List S.Colour)
    (hw : k.dom.WhiskerOK u v) : LinDiagram.whisker k.rel u v hw ∈ P.ideal _ _ := by
  apply Submodule.subset_span
  have := IdealGen.intro (P := P) k u v hw (𝟙 _) (𝟙 _)
  simpa using this

/-- The congruence on the free linear 2-category: `f ~ g` iff `f - g` lies in the ideal. -/
def homRel : HomRel (Free R (Obj S)) := fun a b f g => f - g ∈ P.ideal a b

instance : Congruence P.homRel where
  equivalence :=
    { refl := fun f => by simp [homRel]
      symm := fun {f g} h => by
        rw [homRel, ← neg_sub]; exact Submodule.neg_mem _ h
      trans := fun {f g h} h₁ h₂ => by
        rw [homRel, ← sub_add_sub_cancel f g h]; exact Submodule.add_mem _ h₁ h₂ }
  compLeft := fun f g g' h => by
    rw [homRel, ← Preadditive.comp_sub]; exact P.comp_mem_ideal f h
  compRight := fun g h => by
    rw [homRel, ← Preadditive.sub_comp]; exact P.mem_ideal_comp h g

theorem homRel_add : ∀ ⦃X Y : Free R (Obj S)⦄ (f₁ f₂ g₁ g₂ : X ⟶ Y) (_ : P.homRel f₁ f₂)
    (_ : P.homRel g₁ g₂), P.homRel (f₁ + g₁) (f₂ + g₂) := by
  intro X Y f₁ f₂ g₁ g₂ h₁ h₂
  unfold homRel at *
  rw [add_sub_add_comm]; exact Submodule.add_mem _ h₁ h₂

theorem homRel_smul : ∀ (a : R) ⦃X Y : Free R (Obj S)⦄ (f₁ f₂ : X ⟶ Y) (_ : P.homRel f₁ f₂),
    P.homRel (a • f₁) (a • f₂) := by
  intro a X Y f₁ f₂ h
  unfold homRel at *
  rw [← smul_sub]; exact Submodule.smul_mem _ a h

/-- The presented `R`-linear 2-category. -/
abbrev Presented : Type _ := CategoryTheory.Quotient P.homRel

instance : Preadditive (CategoryTheory.Quotient P.homRel) := CategoryTheory.Quotient.preadditive P.homRel P.homRel_add

instance : (CategoryTheory.Quotient.functor P.homRel).Additive := CategoryTheory.Quotient.functor_additive P.homRel P.homRel_add

instance : Linear R (CategoryTheory.Quotient P.homRel) := CategoryTheory.Quotient.linear R P.homRel P.homRel_smul

/-- The object of the presented category given by an object of the free 2-category. -/
def obj (a : Obj S) : P.Presented := ⟨Free.of R a⟩

/-! ### Instance shortcuts for endomorphism rings

Algebraic instance search on `End X` otherwise explores many unrelated instances on hom types;
these high-priority shortcuts make it immediate. They are all definitionally the instances
inferred from the linear structure. -/

section EndShortcuts

variable (a : Obj S)

instance (priority := high) instEndZero : Zero (End (P.obj a)) := inferInstance
instance (priority := high) instEndOne : One (End (P.obj a)) := inferInstance
instance (priority := high) instEndAdd : Add (End (P.obj a)) := inferInstance
instance (priority := high) instEndMul : Mul (End (P.obj a)) := inferInstance
instance (priority := high) instEndNeg : Neg (End (P.obj a)) := inferInstance
instance (priority := high) instEndSub : Sub (End (P.obj a)) := inferInstance
instance (priority := high) instEndAddZeroClass : AddZeroClass (End (P.obj a)) := inferInstance
instance (priority := high) instEndMulZeroClass : MulZeroClass (End (P.obj a)) := inferInstance
instance (priority := high) instEndMulOneClass : MulOneClass (End (P.obj a)) := inferInstance
instance (priority := high) instEndAddCommMagma : AddCommMagma (End (P.obj a)) := inferInstance
instance (priority := high) instEndDistrib : Distrib (End (P.obj a)) := inferInstance
instance (priority := high) instEndAddSemigroup : AddSemigroup (End (P.obj a)) := inferInstance
instance (priority := high) instEndSemigroup : Semigroup (End (P.obj a)) := inferInstance
instance (priority := high) instEndAddMonoid : AddMonoid (End (P.obj a)) := inferInstance
instance (priority := high) instEndMonoid : Monoid (End (P.obj a)) := inferInstance
instance (priority := high) instEndAddCommMonoid : AddCommMonoid (End (P.obj a)) := inferInstance
instance (priority := high) instEndAddGroup : AddGroup (End (P.obj a)) := inferInstance
instance (priority := high) instEndSubNegMonoid : SubNegMonoid (End (P.obj a)) := inferInstance
instance (priority := high) instEndAddCommGroup : AddCommGroup (End (P.obj a)) := inferInstance
instance (priority := high) instEndNonUnitalNonAssocSemiring : NonUnitalNonAssocSemiring (End (P.obj a)) := inferInstance
instance (priority := high) instEndNonAssocSemiring : NonAssocSemiring (End (P.obj a)) := inferInstance
instance (priority := high) instEndSemiring : Semiring (End (P.obj a)) := inferInstance
instance (priority := high) instEndNonUnitalNonAssocRing : NonUnitalNonAssocRing (End (P.obj a)) := inferInstance
instance (priority := high) instEndNonAssocRing : NonAssocRing (End (P.obj a)) := inferInstance
instance (priority := high) instEndRing : Ring (End (P.obj a)) := inferInstance
instance (priority := high) instEndMonoidWithZero : MonoidWithZero (End (P.obj a)) := inferInstance
instance (priority := high) instEndSubtractionMonoid : SubtractionMonoid (End (P.obj a)) := inferInstance
instance (priority := high) instEndNegZeroClass : NegZeroClass (End (P.obj a)) := inferInstance
instance (priority := high) instEndHasDistribNeg : HasDistribNeg (End (P.obj a)) := inferInstance
instance (priority := high) instEndAddGroupWithOne : AddGroupWithOne (End (P.obj a)) := inferInstance
instance (priority := high) instEndAddMonoidWithOne : AddMonoidWithOne (End (P.obj a)) := inferInstance
instance (priority := high) instEndSMul : SMul R (End (P.obj a)) := inferInstance
instance (priority := high) instEndModule : Module R (End (P.obj a)) := inferInstance
instance (priority := high) instEndAlgebra : Algebra R (End (P.obj a)) := inferInstance

end EndShortcuts

/-- The quotient functor from linear combinations of diagrams. -/
def linFunctor : Free R (Obj S) ⥤ P.Presented := CategoryTheory.Quotient.functor P.homRel

instance : P.linFunctor.Full := inferInstanceAs (CategoryTheory.Quotient.functor P.homRel).Full

instance : P.linFunctor.Additive := inferInstanceAs (CategoryTheory.Quotient.functor P.homRel).Additive

instance : P.linFunctor.Linear R := CategoryTheory.Quotient.linear_functor R P.homRel P.homRel_smul

/-- The class of a linear combination of diagrams in the presented category. -/
def lin {a b : Obj S} (f : LinDiagram R a b) : P.obj a ⟶ P.obj b := P.linFunctor.map f

/-- The class of a diagram in the presented category. -/
def diag {a b : Obj S} (f : a ⟶ b) : P.obj a ⟶ P.obj b := P.lin (LinDiagram.of f)

/-- The class of a single layer, typed along equalities of objects. -/
def layer (L : Layer S) (hv : L.Valid) {a b : Obj S} (ha : L.dom = a)
    (hb : L.cod = b) : P.obj a ⟶ P.obj b :=
  P.diag (Diagram.layer L hv ha hb)

@[simp] theorem lin_comp {a b c : Obj S} (f : LinDiagram R a b) (g : LinDiagram R b c) :
    P.lin (f ≫ g) = P.lin f ≫ P.lin g := P.linFunctor.map_comp f g

@[simp] theorem lin_add {a b : Obj S} (f g : LinDiagram R a b) :
    P.lin (f + g) = P.lin f + P.lin g := P.linFunctor.map_add

@[simp] theorem lin_sub {a b : Obj S} (f g : LinDiagram R a b) :
    P.lin (f - g) = P.lin f - P.lin g := P.linFunctor.map_sub

@[simp] theorem lin_neg {a b : Obj S} (f : LinDiagram R a b) :
    P.lin (-f) = -P.lin f := P.linFunctor.map_neg

@[simp] theorem lin_zero {a b : Obj S} : P.lin (0 : LinDiagram R a b) = 0 :=
  P.linFunctor.map_zero _ _

@[simp] theorem lin_smul {a b : Obj S} (r : R) (f : LinDiagram R a b) :
    P.lin (r • f) = r • P.lin f := P.linFunctor.map_smul r f

@[simp] theorem lin_id (a : Obj S) : P.lin (𝟙 (Free.of R a)) = 𝟙 (P.obj a) :=
  P.linFunctor.map_id _

theorem lin_single {a b : Obj S} (f : a ⟶ b) (r : R) :
    P.lin (Finsupp.single f r : LinDiagram R a b) = r • P.diag f := by
  rw [diag, ← lin_smul, Finsupp.smul_single, smul_eq_mul, mul_one]

@[simp] theorem diag_comp {a b c : Obj S} (f : a ⟶ b) (g : b ⟶ c) :
    P.diag (f ≫ g) = P.diag f ≫ P.diag g := by
  rw [diag, LinDiagram.of_comp, lin_comp]; rfl

@[simp] theorem diag_id (a : Obj S) : P.diag (𝟙 a) = 𝟙 (P.obj a) := P.lin_id a

theorem diag_eq_of_layers_eq {a b : Obj S} {f g : a ⟶ b}
    (h : Diagram.layers f = Diagram.layers g) : P.diag f = P.diag g := by
  rw [Diagram.ext h]

theorem lin_eq_iff {a b : Obj S} (f g : LinDiagram R a b) :
    P.lin f = P.lin g ↔ f - g ∈ P.ideal a b :=
  CategoryTheory.Quotient.functor_map_eq_iff P.homRel f g

/-- Every whiskered relation holds in the presented category. -/
theorem lin_rel (i : P.Rel) (u : Obj S) (v : List S.Colour) (hw : (P.dom i).WhiskerOK u v) :
    P.lin (LinDiagram.whisker (P.rel i) u v hw) = 0 := by
  rw [← P.lin_zero, lin_eq_iff, sub_zero]
  exact P.whisker_rel_mem_ideal (.user i) u v hw

/-- Every whiskered relation holds in the presented category, typed along equalities of
objects. This is the form used to transport a relation to a symbolic position. -/
theorem lin_rel_cast (i : P.Rel) (u : Obj S) (v : List S.Colour) (hw : (P.dom i).WhiskerOK u v)
    {a b : Obj S} (ha : (P.dom i).whisker u v = a) (hb : (P.cod i).whisker u v = b) :
    P.lin (LinDiagram.cast (LinDiagram.whisker (P.rel i) u v hw) ha hb) = 0 := by
  subst ha hb; rw [LinDiagram.cast_rfl]; exact P.lin_rel i u v hw

@[simp] theorem lin_of {a b : Obj S} (f : a ⟶ b) : P.lin (LinDiagram.of f) = P.diag f := rfl

/-- Every whiskered instance of the interchange law holds in the presented category. -/
theorem lin_interchange (x : InterchangeData S) (hx : x.Valid) (u : Obj S) (v : List S.Colour)
    (hw : x.dom.WhiskerOK u v) :
    P.lin (LinDiagram.whisker (InterchangeData.rel R hx) u v hw) = 0 := by
  rw [← P.lin_zero, lin_eq_iff, sub_zero]
  exact P.whisker_rel_mem_ideal (.interchange x hx) u v hw

/-- Every whiskered instance of the interchange law holds in the presented category, typed
along equalities of objects. -/
theorem lin_interchange_cast (x : InterchangeData S) (hx : x.Valid) (u : Obj S)
    (v : List S.Colour) (hw : x.dom.WhiskerOK u v) {a b : Obj S} (ha : x.dom.whisker u v = a)
    (hb : x.cod.whisker u v = b) :
    P.lin (LinDiagram.cast (LinDiagram.whisker (InterchangeData.rel R hx) u v hw) ha hb) = 0 := by
  subst ha hb; rw [LinDiagram.cast_rfl]; exact P.lin_interchange x hx u v hw

/-- The interchange law at a whiskered, retyped position, in terms of diagrams. -/
theorem diag_interchange (x : InterchangeData S) (hx : x.Valid) (u : Obj S)
    (v : List S.Colour) (hw : x.dom.WhiskerOK u v) {a b : Obj S} (ha : x.dom.whisker u v = a)
    (hb : x.cod.whisker u v = b) :
    P.diag (Diagram.cast (Diagram.whisker (InterchangeData.ghDiagram hx) u v hw) ha hb) =
      ((x.sign : ℤ) : R) •
        P.diag (Diagram.cast (Diagram.whisker (InterchangeData.hgDiagram hx) u v hw) ha hb) := by
  have := P.lin_interchange_cast x hx u v hw ha hb
  rw [InterchangeData.rel, LinDiagram.whisker_sub, LinDiagram.whisker_smul, LinDiagram.cast_sub,
    LinDiagram.cast_smul, LinDiagram.whisker_of, LinDiagram.whisker_of, LinDiagram.cast_of,
    LinDiagram.cast_of, lin_sub, lin_smul, lin_of, lin_of, sub_eq_zero] at this
  exact this

end Presentation

end StringDiagrams

end
