import StringDiagrams.Derivation
import StringDiagrams.Examples.Exterior

/-!
# Examples of local derivations

Two tests of `StringDiagrams.Derivation`, on the signature of `StringDiagrams.Exterior`
(one region, one strand colour, one odd dot).

* `SkewPolynomial`: no relations besides the super interchange law, so the endomorphism
  algebra of `n` strands is generated by pairwise anticommuting dots `x n i` (the skew
  polynomial superalgebra `OPol_n` of Ellis–Qi, arXiv:1504.01712v2, Example 2.11). With
  `δ(dot) = dot ≫ dot` we recover the differential of Ellis–Qi (2.18): `d(x_i) = x_i²`
  (`d_x`), the Leibniz rule `d(x_i x_j) = x_i² x_j - x_i x_j²` (`d_x_mul_x`), and `d² = 0`
  (`d_d`), the latter checked on the generator: `d(x²) = d(x) x - x d(x) = x³ - x³ = 0`.
* `ExteriorDeriv`: the relation `dot ≫ dot = 0` of `Exterior.pres`, with `δ(dot) = 1`
  (the identity strand, even). This is compatible with the relation, since
  `d(x²) = d(x) x - x d(x) = x - x = 0`, and gives `d(x_i) = 1`, `d(x_i x_j) = x_j - x_i`
  and `d² = 0`.
-/

noncomputable section

namespace StringDiagrams.SkewPolynomial

open CategoryTheory Exterior Diagram

variable (R : Type*) [CommRing R]

/-- One odd dot and no relations besides the super interchange law. -/
def pres : Presentation sig R where
  Rel := Empty
  dom := Empty.elim
  cod := Empty.elim
  rel i := i.elim

/-- The local derivation `δ(dot) = dot ≫ dot`. -/
def D : LocalDerivation sig R where
  δ _ := LinDiagram.of (ofGen Gen.dot ≫ ofGen Gen.dot)
  hasParity _ := LinDiagram.hasParity_of rfl

theorem compatible : (D R).Compatible (pres R) :=
  ⟨fun i => i.elim, fun i => i.elim⟩

/-- The differential on the endomorphism algebra of `n` strands. -/
abbrev d (n : ℕ) : End ((pres R).obj (strands n)) →ₗ[R] End ((pres R).obj (strands n)) :=
  (pres R).derivEnd (compatible R) (strands n)

/-- A dot on strand `i` of `n` (zero if `i ≥ n`). -/
def x (n i : ℕ) : End ((pres R).obj (strands n)) :=
  if h : i < n then (pres R).diag (dlay h) else 0

theorem x_eq_lin {n i : ℕ} (h : i < n) :
    (pres R).lin (LinDiagram.of (dlay h)) = x R n i := by
  rw [x, dif_pos h]; rfl

/-- `d(x_i) = x_i²`: Ellis–Qi (2.18). -/
theorem d_x (n i : ℕ) : d R n (x R n i) = x R n i * x R n i := by
  by_cases h : i < n
  · rw [x, dif_pos h, Presentation.derivEnd_apply, dlay,
      Presentation.deriv_layer_of _ _ _ _ _ _ (ofGen Gen.dot ≫ ofGen Gen.dot) rfl, End.mul_def,
      ← Presentation.diag_comp]
    apply Presentation.diag_eq_of_layers_eq
    simp [lay, Layer.whisker, Signature.genLayer]
  · simp [x, dif_neg h]

/-- The Leibniz rule on a product of two dots: `d(x_i x_j) = x_i² x_j - x_i x_j²`. -/
theorem d_x_mul_x (n i j : ℕ) :
    d R n (x R n i * x R n j) = x R n i * x R n i * x R n j - x R n i * (x R n j * x R n j) := by
  by_cases h : i < n
  · rw [Presentation.deriv_mul _ _ _ _ (LinDiagram.hasParity_of (p := 1) rfl) (x_eq_lin R h),
      d_x, d_x, pow_one, neg_one_smul, sub_eq_add_neg]
  · simp [x, dif_neg h]

theorem d_ofGen_ofGen :
    (pres R).deriv (compatible R) ((pres R).diag (ofGen Gen.dot)) =
      (pres R).diag (ofGen Gen.dot) ≫ (pres R).diag (ofGen Gen.dot) := by
  rw [Presentation.deriv_ofGen]
  show (pres R).lin (LinDiagram.of (ofGen Gen.dot ≫ ofGen Gen.dot)) = _
  rw [Presentation.lin_of, Presentation.diag_comp]

/-- `d² = 0`, checked on the generator. -/
theorem d_d {a b : Obj sig} (f : (pres R).obj a ⟶ (pres R).obj b) :
    (pres R).deriv (compatible R) ((pres R).deriv (compatible R) f) = 0 := by
  refine Presentation.deriv_deriv_eq_zero _ _ (fun g => ?_) f
  cases g
  rw [d_ofGen_ofGen, Presentation.deriv_comp_diag]
  erw [d_ofGen_ofGen]
  rw [oddCount_ofGen]
  show ((-1 : R) ^ 1) • _ + _ = 0
  rw [pow_one, neg_one_smul, Category.assoc, neg_add_cancel]

theorem d_d_x (n i : ℕ) : d R n (d R n (x R n i)) = 0 := d_d R _

end StringDiagrams.SkewPolynomial

namespace StringDiagrams.ExteriorDeriv

open CategoryTheory Exterior Diagram

variable (R : Type*) [CommRing R]

/-- The local derivation `δ(dot) = 1` (the identity strand). -/
def D : LocalDerivation sig R where
  δ g := LinDiagram.of (𝟙 (sig.genDom g))
  hasParity g := LinDiagram.hasParity_of (by rw [show sig.odd g = true from rfl]; simp [oddCount])

theorem derivDiag_dlay {n i : ℕ} (h : i < n) :
    (D R).derivDiag (dlay h) = 𝟙 (Free.of R (strands n)) := by
  rw [dlay, LocalDerivation.derivDiag_layer_of _ _ _ _ _ (𝟙 (sig.genDom Gen.dot)) rfl]
  show LinDiagram.of _ = LinDiagram.of (𝟙 (strands n))
  congr 1

/-- `δ(dot) = 1` is compatible with the relation `dot ≫ dot = 0`: already in the free
category, `d(dot ≫ dot) = -(1 ≫ dot) + dot ≫ 1 = 0`. -/
theorem compatible : (D R).Compatible (pres R) := by
  refine ⟨fun _ => ⟨2, LinDiagram.hasParity_of rfl⟩, fun _ => ?_⟩
  show (pres R).lin ((D R).derivFree (LinDiagram.of (dlay _ ≫ dlay _))) = 0
  rw [LocalDerivation.derivFree_of, LocalDerivation.derivDiag_comp, derivDiag_dlay]
  show (pres R).lin (((-1 : R) ^ 1) • _ + _) = 0
  rw [pow_one, neg_one_smul, Category.id_comp, Category.comp_id, neg_add_cancel,
    Presentation.lin_zero]

/-- The differential on the endomorphism algebra of `n` strands. -/
abbrev d (n : ℕ) : End ((pres R).obj (strands n)) →ₗ[R] End ((pres R).obj (strands n)) :=
  (pres R).derivEnd (compatible R) (strands n)

theorem d_x {n i : ℕ} (h : i < n) : d R n (x R n i) = 1 := by
  rw [x_def R h, Presentation.derivEnd_apply, Presentation.deriv_diag, derivDiag_dlay,
    Presentation.lin_id]
  rfl

theorem d_x_mul_x {n i j : ℕ} (hi : i < n) (hj : j < n) :
    d R n (x R n i * x R n j) = x R n j - x R n i := by
  rw [Presentation.deriv_mul _ _ _ _ (LinDiagram.hasParity_of (p := 1) rfl)
      (x_def R hi).symm, d_x R hi, d_x R hj, pow_one, neg_one_smul, one_mul, mul_one,
    sub_eq_add_neg]

/-- `d² = 0`, checked on the generator: `d(d(dot)) = d(1) = 0`. -/
theorem d_d {a b : Obj sig} (f : (pres R).obj a ⟶ (pres R).obj b) :
    (pres R).deriv (compatible R) ((pres R).deriv (compatible R) f) = 0 := by
  refine Presentation.deriv_deriv_eq_zero _ _ (fun g => ?_) f
  rw [Presentation.deriv_ofGen]
  show (pres R).deriv (compatible R) ((pres R).lin (𝟙 (Free.of R (sig.genDom g)))) = 0
  rw [Presentation.lin_id, Presentation.deriv_id]

end StringDiagrams.ExteriorDeriv

end
