import StringDiagrams.Interpretation

/-!
# Odd dots: exterior algebras from the super interchange law

A test of the Koszul sign in the interchange law. The signature has one region, one strand
colour and a single *odd* generator, a dot. Imposing only `dot ≫ dot = 0`, the endomorphism
algebra of `n` strands is generated by dots `x n i` which anticommute by the super
interchange law alone (`x_mul_x_anticomm`) and square to zero (`x_mul_x_self`): it is a
quotient of the exterior algebra on `n` generators.
-/

noncomputable section

namespace StringDiagrams.Exterior

open CategoryTheory

/-- The single generator. -/
inductive Gen
  | dot
  deriving DecidableEq

/-- One region, one colour, one odd dot. -/
def sig : Signature where
  Region := Unit
  Colour := Unit
  colourSrc _ := ()
  colourTgt _ := ()
  Gen := Gen
  dom _ := [()]
  cod _ := [()]
  left _ := ()
  right _ := ()
  odd _ := true

instance : Subsingleton sig.Region := inferInstanceAs (Subsingleton Unit)

/-- `n` strands. -/
def strands (n : ℕ) : Obj sig := ⟨(), List.replicate n ()⟩

theorem list_unit_ext {l₁ l₂ : List Unit} (h : l₁.length = l₂.length) : l₁ = l₂ := by
  induction l₁ generalizing l₂ with
  | nil => cases l₂ with
    | nil => rfl
    | cons _ _ => simp at h
  | cons a l ih => cases l₂ with
    | nil => simp at h
    | cons b l₂ => rw [ih (by simpa using h)]

@[simp] theorem word_eq_iff {l₁ l₂ : List sig.Colour} : l₁ = l₂ ↔ l₁.length = l₂.length :=
  ⟨congrArg List.length, list_unit_ext⟩

@[simp] theorem list_unit_eq_iff {l₁ l₂ : List Unit} : l₁ = l₂ ↔ l₁.length = l₂.length :=
  ⟨congrArg List.length, list_unit_ext⟩

theorem obj_ext {a b : Obj sig} (h : a.word.length = b.word.length) : a = b :=
  Obj.ext (Subsingleton.elim (α := Unit) _ _) (list_unit_ext h)

/-- The dot with `i` strands to its left, on `n` strands. -/
def lay (n i : ℕ) : Layer sig := ⟨(), List.replicate i (), .dot, List.replicate (n - i - 1) ()⟩

theorem lay_dom {n i : ℕ} (h : i < n) : (lay n i).dom = strands n :=
  obj_ext (by simp [lay, Layer.dom, strands, sig]; omega)

theorem lay_cod {n i : ℕ} (h : i < n) : (lay n i).cod = strands n :=
  obj_ext (by simp [lay, Layer.cod, strands, sig]; omega)

/-- The dot as an endomorphism of `n` strands in the free 2-category. -/
def dlay {n i : ℕ} (h : i < n) : strands n ⟶ strands n :=
  Diagram.layer (lay n i) (Layer.valid_of_subsingleton _) (lay_dom h) (lay_cod h)

variable (R : Type*) [CommRing R]

/-- The single relation `dot ≫ dot = 0` on one strand. -/
def pres : Presentation sig R where
  Rel := Unit
  dom _ := strands 1
  cod _ := strands 1
  rel _ := LinDiagram.of (dlay (n := 1) (i := 0) (by decide) ≫ dlay (n := 1) (i := 0) (by decide))

/-- A dot on strand `i` of `n` (zero if `i ≥ n`). -/
def x (n i : ℕ) : End ((pres R).obj (strands n)) :=
  if h : i < n then (pres R).diag (dlay h) else 0

theorem x_def {n i : ℕ} (h : i < n) : x R n i = (pres R).diag (dlay h) := dif_pos h

/-- `i` strands, used to whisker on the left. -/
def shift (i : ℕ) : Obj sig := ⟨(), List.replicate i ()⟩

theorem x_mul_x_self (n i : ℕ) : x R n i * x R n i = 0 := by
  by_cases h : i < n
  · have key := (pres R).lin_rel_cast () (shift i) (List.replicate (n - i - 1) ())
      (Obj.whiskerOK_of_subsingleton _ _ _) (a := strands n) (b := strands n)
      (obj_ext (by simp [pres, strands, shift, Obj.whisker]; omega))
      (obj_ext (by simp [pres, strands, shift, Obj.whisker]; omega))
    rw [show (pres R).rel () = LinDiagram.of _ from rfl, LinDiagram.whisker_of,
      LinDiagram.cast_of, Presentation.lin_of] at key
    rw [x_def R h, End.mul_def, ← Presentation.diag_comp, ← key]
    apply Presentation.diag_eq_of_layers_eq
    simp [dlay, lay, shift, Layer.whisker]
  · rw [x, dif_neg h, mul_zero]

/-- Distinct dots anticommute: the super interchange law with two odd generators. -/
theorem x_mul_x_anticomm {n i j : ℕ} (hij : i < j) : x R n i * x R n j = -(x R n j * x R n i) := by
  by_cases hj : j < n
  · let d : InterchangeData sig := ⟨(), .dot, List.replicate (j - i - 1) (), .dot⟩
    have hx : d.Valid := InterchangeData.valid_of_subsingleton d
    have hd : d.dom.whisker (shift i) (List.replicate (n - j - 1) ()) = strands n :=
      obj_ext (by simp [d, InterchangeData.dom, shift, strands, sig]; omega)
    have hc : d.cod.whisker (shift i) (List.replicate (n - j - 1) ()) = strands n :=
      obj_ext (by simp [d, InterchangeData.cod, shift, strands, sig]; omega)
    have key := (pres R).diag_interchange d hx (shift i) _
      (Obj.whiskerOK_of_subsingleton _ _ _) hd hc
    have hs : ((d.sign : ℤ) : R) = -1 := by simp [d, InterchangeData.sign, sig]
    rw [hs, neg_one_smul] at key
    rw [x_def R (show i < n by omega), x_def R hj, End.mul_def, End.mul_def,
      ← Presentation.diag_comp, ← Presentation.diag_comp]
    have e₁ : (pres R).diag (dlay (show i < n by omega) ≫ dlay hj) =
        (pres R).diag (Diagram.cast (Diagram.whisker (InterchangeData.ghDiagram hx) (shift i)
          (List.replicate (n - j - 1) ()) (Obj.whiskerOK_of_subsingleton _ _ _)) hd hc) := by
      apply Presentation.diag_eq_of_layers_eq
      simp [d, dlay, lay, shift, Layer.whisker, InterchangeData.ghDiagram, InterchangeData.gh₁,
        InterchangeData.gh₂, sig]
      omega
    have e₂ : (pres R).diag (dlay hj ≫ dlay (show i < n by omega)) =
        (pres R).diag (Diagram.cast (Diagram.whisker (InterchangeData.hgDiagram hx) (shift i)
          (List.replicate (n - j - 1) ()) (Obj.whiskerOK_of_subsingleton _ _ _)) hd hc) := by
      apply Presentation.diag_eq_of_layers_eq
      simp [d, dlay, lay, shift, Layer.whisker, InterchangeData.hgDiagram, InterchangeData.hg₁,
        InterchangeData.hg₂, sig]
      omega
    rw [e₂, e₁, key, neg_neg]
  · simp only [x, dif_neg hj]; simp

end StringDiagrams.Exterior

end
