import StringDiagrams.Super.PiCategory
import Mathlib.CategoryTheory.Preadditive.Biproducts
import Mathlib.CategoryTheory.Preadditive.AdditiveFunctor
import Mathlib.CategoryTheory.Limits.Preserves.Shapes.Biproducts
import Mathlib.GroupTheory.FreeAbelianGroup
import Mathlib.GroupTheory.QuotientGroup.Defs
import Mathlib.Algebra.Polynomial.Eval.Defs
import Mathlib.Algebra.Polynomial.Basic
import Mathlib.RingTheory.Ideal.Quotient.Defs
import Mathlib.RingTheory.Ideal.Span
import Mathlib.Algebra.Module.Hom
import Mathlib.CategoryTheory.Monoidal.Preadditive

/-!
# The split Grothendieck group, and the ring `Zπ`

Following J. Brundan, A. P. Ellis, *Monoidal supercategories*, arXiv:1603.05928v3, §1.5.

* `K₀ C`: the split Grothendieck group of a preadditive category with binary biproducts: the
  abelian group generated by the isomorphism classes `[V]` of objects subject to
  `[V ⊕ W] = [V] + [W]`. We present it as the free abelian group on the objects modulo the
  relations `[V] = [W]` for `V ≅ W` and `[V ⊞ W] = [V] + [W]`. Universal property: `K₀.lift`,
  `K₀.lift_mk`, `K₀.hom_ext`. Every class is a difference `[V] - [W]` (`K₀.exists_eq_mk_sub_mk`,
  when `C` has a zero object). Additive functors induce group homomorphisms (`K₀.map`), and
  isomorphic functors induce the same one (`K₀.map_eq_of_iso`).
* `Zπ := ℤ[π]/(π² − 1)` (`StringDiagrams.Zπ`, `Zπ.π`, `Zπ.π_mul_π`), and the `Zπ`-module
  structure on an abelian group with an involution (`Zπ.moduleOfInvolution`).
* For a Π-category `(A, Π, ξ)` with binary biproducts, `π([V]) := [Π V]` is an involution of
  `K₀ A` (`K₀.piInvolution`, `K₀.piInvolution_piInvolution`), making `K₀ A` a `Zπ`-module
  (`K₀.moduleZπ`, `K₀.π_smul_mk`).
-/

noncomputable section

namespace StringDiagrams

open CategoryTheory Limits

universe w v u v' u' v''

variable (C : Type u) [Category.{v} C] [Preadditive C] [HasBinaryBiproducts C]

/-- The relations of the split Grothendieck group: `[V] - [W]` for `V ≅ W`, and
`[V ⊞ W] - [V] - [W]`. -/
def K₀.relations : AddSubgroup (FreeAbelianGroup C) :=
  AddSubgroup.closure
    ({x | ∃ (X Y : C) (_ : X ≅ Y), x = FreeAbelianGroup.of X - FreeAbelianGroup.of Y} ∪
      {x | ∃ X Y : C, x = FreeAbelianGroup.of (X ⊞ Y) - FreeAbelianGroup.of X -
        FreeAbelianGroup.of Y})

/-- **Brundan–Ellis, §1.5.** The split Grothendieck group `K₀(C)` of a preadditive category with
binary biproducts: generated by the isomorphism classes of objects, subject to
`[V ⊕ W] = [V] + [W]`. -/
def K₀ : Type u := FreeAbelianGroup C ⧸ K₀.relations C

namespace K₀

instance : AddCommGroup (K₀ C) := inferInstanceAs (AddCommGroup (FreeAbelianGroup C ⧸ _))

variable {C}

/-- The class `[X]` of an object. -/
def mk (X : C) : K₀ C := QuotientAddGroup.mk (s := relations C) (FreeAbelianGroup.of X)

theorem mk_eq_mk_of_iso {X Y : C} (e : X ≅ Y) : mk X = mk Y := by
  rw [mk, mk, QuotientAddGroup.eq_iff_sub_mem]
  exact AddSubgroup.subset_closure (Or.inl ⟨X, Y, e, rfl⟩)

/-- `[V ⊞ W] = [V] + [W]`. -/
theorem mk_biprod (X Y : C) : mk (X ⊞ Y) = mk X + mk Y := by
  rw [← sub_eq_zero, sub_add_eq_sub_sub, mk, mk, mk, ← QuotientAddGroup.mk_sub,
    ← QuotientAddGroup.mk_sub, QuotientAddGroup.eq_zero_iff]
  exact AddSubgroup.subset_closure (Or.inr ⟨X, Y, rfl⟩)

/-- The classes of any binary biproduct add. -/
theorem mk_of_isBilimit {X Y : C} (b : BinaryBicone X Y) (hb : b.IsBilimit) :
    mk b.pt = mk X + mk Y := by
  rw [mk_eq_mk_of_iso (biprod.uniqueUpToIso X Y hb), mk_biprod]

section Lift

variable {G : Type w} [AddCommGroup G] (f : C → G) (hiso : ∀ X Y : C, (X ≅ Y) → f X = f Y)
  (hbiprod : ∀ X Y : C, f (X ⊞ Y) = f X + f Y)

/-- **Universal property of `K₀`.** A function on objects which is invariant under isomorphism
and additive on biproducts induces a homomorphism `K₀ C →+ G`. -/
def lift : K₀ C →+ G :=
  QuotientAddGroup.lift (relations C) (FreeAbelianGroup.lift f) (by
    refine (AddSubgroup.closure_le _).2 ?_
    rintro x (⟨X, Y, e, rfl⟩ | ⟨X, Y, rfl⟩)
    · simp [hiso X Y e]
    · simp [hbiprod])

@[simp] theorem lift_mk (X : C) : lift f hiso hbiprod (mk X) = f X :=
  FreeAbelianGroup.lift.of f X

end Lift

/-- Homomorphisms out of `K₀ C` are determined by their values on classes of objects. -/
theorem hom_ext {G : Type w} [AddCommGroup G] {φ ψ : K₀ C →+ G} (h : ∀ X : C, φ (mk X) = ψ (mk X)) :
    φ = ψ := by
  apply QuotientAddGroup.addMonoidHom_ext
  apply FreeAbelianGroup.lift.ext
  exact h

/-- Induction on elements of `K₀ C`. -/
@[elab_as_elim]
theorem induction_on {P : K₀ C → Prop} (x : K₀ C) (mk : ∀ X, P (mk X)) (zero : P 0)
    (add : ∀ x y, P x → P y → P (x + y)) (neg : ∀ x, P x → P (-x)) : P x := by
  induction x using QuotientAddGroup.induction_on with
  | H z =>
    induction z using FreeAbelianGroup.induction_on with
    | C0 => exact zero
    | C1 X => exact mk X
    | Cn X h => exact neg _ h
    | Cp a b ha hb => exact add _ _ ha hb

open ZeroObject in
theorem mk_zero [HasZeroObject C] : mk (0 : C) = 0 := by
  have h := mk_biprod (0 : C) 0
  have hz : IsZero ((0 : C) ⊞ 0) := by
    rw [IsZero.iff_id_eq_zero]
    apply biprod.hom_ext <;> exact (isZero_zero C).eq_of_tgt _ _
  rw [mk_eq_mk_of_iso (hz.iso (isZero_zero C))] at h
  exact left_eq_add.mp h

open ZeroObject in
/-- In an additive category every element of `K₀` is a difference of classes. -/
theorem exists_eq_mk_sub_mk [HasZeroObject C] (x : K₀ C) : ∃ X Y : C, x = mk X - mk Y := by
  induction x using induction_on with
  | mk X => exact ⟨X, 0, by rw [mk_zero, sub_zero]⟩
  | zero => exact ⟨0, 0, by rw [sub_self]⟩
  | add x y hx hy =>
    obtain ⟨X, Y, rfl⟩ := hx
    obtain ⟨X', Y', rfl⟩ := hy
    exact ⟨X ⊞ X', Y ⊞ Y', by rw [mk_biprod, mk_biprod]; abel⟩
  | neg x hx =>
    obtain ⟨X, Y, rfl⟩ := hx
    exact ⟨Y, X, by abel⟩

/-! ## Functoriality -/

section Map

variable {D : Type u'} [Category.{v'} D] [Preadditive D] [HasBinaryBiproducts D]
  {E : Type w} [Category.{v''} E] [Preadditive E] [HasBinaryBiproducts E]

/-- An additive functor preserves binary biproducts. -/
@[simps]
def mapBiprodIso (F : C ⥤ D) [F.Additive] (X Y : C) : F.obj (X ⊞ Y) ≅ F.obj X ⊞ F.obj Y where
  hom := biprod.lift (F.map biprod.fst) (F.map biprod.snd)
  inv := biprod.desc (F.map biprod.inl) (F.map biprod.inr)
  hom_inv_id := by
    rw [biprod.lift_desc, ← F.map_comp, ← F.map_comp, ← F.map_add, biprod.total, F.map_id]
  inv_hom_id := by
    apply biprod.hom_ext' <;> apply biprod.hom_ext <;>
      simp [← F.map_comp]

/-- The homomorphism `K₀ C →+ K₀ D` induced by an additive functor. -/
def map (F : C ⥤ D) [F.Additive] : K₀ C →+ K₀ D :=
  lift (fun X => mk (F.obj X)) (fun _ _ e => mk_eq_mk_of_iso (F.mapIso e))
    (fun X Y => by
      show mk (F.obj (X ⊞ Y)) = mk (F.obj X) + mk (F.obj Y)
      rw [mk_eq_mk_of_iso (mapBiprodIso F X Y), mk_biprod])

@[simp] theorem map_mk (F : C ⥤ D) [F.Additive] (X : C) : map F (mk X) = mk (F.obj X) := by
  rw [map, lift_mk]

theorem map_id : map (𝟭 C) = AddMonoidHom.id (K₀ C) :=
  hom_ext fun X => by simp

theorem map_comp (F : C ⥤ D) [F.Additive] (G : D ⥤ E) [G.Additive] :
    map (F ⋙ G) = (map G).comp (map F) :=
  hom_ext fun X => by simp

/-- Isomorphic additive functors induce the same homomorphism. -/
theorem map_eq_of_iso {F G : C ⥤ D} [F.Additive] [G.Additive] (e : F ≅ G) : map F = map G :=
  hom_ext fun X => by rw [map_mk, map_mk, mk_eq_mk_of_iso (e.app X)]

/-- An additive equivalence of categories induces an isomorphism of split Grothendieck groups. -/
def mapEquiv (e : C ≌ D) [e.functor.Additive] : K₀ C ≃+ K₀ D where
  toFun := map e.functor
  invFun := map e.inverse
  left_inv x := by
    rw [← AddMonoidHom.comp_apply, ← map_comp, map_eq_of_iso e.unitIso.symm, map_id,
      AddMonoidHom.id_apply]
  right_inv x := by
    rw [← AddMonoidHom.comp_apply, ← map_comp, map_eq_of_iso e.counitIso, map_id,
      AddMonoidHom.id_apply]
  map_add' := map_add (map e.functor)

@[simp] theorem mapEquiv_mk (e : C ≌ D) [e.functor.Additive] (X : C) :
    mapEquiv e (mk X) = mk (e.functor.obj X) :=
  map_mk _ _

end Map

/-! ## The ring structure for monoidal categories -/

section Ring

open MonoidalCategory

variable [MonoidalCategory C] [MonoidalPreadditive C]

/-- The multiplication `[X] · [Y] = [X ⊗ Y]` on `K₀` of a monoidal additive category. -/
def mulHom : K₀ C →+ K₀ C →+ K₀ C :=
  lift (fun X => lift (fun Y => mk (X ⊗ Y)) (fun _ _ e => mk_eq_mk_of_iso (whiskerLeftIso X e))
      (fun Y Y' => (mk_eq_mk_of_iso (mapBiprodIso (tensorLeft X) Y Y')).trans (mk_biprod _ _)))
    (fun X X' e => hom_ext fun Y => by
      simp only [lift_mk]; exact mk_eq_mk_of_iso (whiskerRightIso e Y))
    (fun X X' => hom_ext fun Y => by
      simp only [lift_mk, AddMonoidHom.add_apply]
      exact (mk_eq_mk_of_iso (mapBiprodIso (tensorRight Y) X X')).trans (mk_biprod _ _))

instance : Mul (K₀ C) := ⟨fun x y => mulHom x y⟩

instance : One (K₀ C) := ⟨mk (𝟙_ C)⟩

theorem mul_def (x y : K₀ C) : x * y = mulHom x y := rfl

@[simp] theorem mk_mul_mk (X Y : C) : mk X * mk Y = mk (X ⊗ Y) := by
  simp [mul_def, mulHom]

omit [MonoidalPreadditive C] in
theorem one_def : (1 : K₀ C) = mk (𝟙_ C) := rfl

protected theorem mul_add (x y z : K₀ C) : x * (y + z) = x * y + x * z := map_add (mulHom x) y z

protected theorem add_mul (x y z : K₀ C) : (x + y) * z = x * z + y * z := by
  simp only [mul_def, map_add, AddMonoidHom.add_apply]

protected theorem mul_zero (x : K₀ C) : x * 0 = 0 := map_zero (mulHom x)

protected theorem zero_mul (x : K₀ C) : 0 * x = 0 := by
  simp only [mul_def, map_zero, AddMonoidHom.zero_apply]

protected theorem mul_neg (x y : K₀ C) : x * -y = -(x * y) := map_neg (mulHom x) y

protected theorem neg_mul (x y : K₀ C) : -x * y = -(x * y) := by
  simp only [mul_def, map_neg, AddMonoidHom.neg_apply]

protected theorem mul_assoc (x y z : K₀ C) : x * y * z = x * (y * z) := by
  induction x using induction_on with
  | mk X =>
    induction y using induction_on with
    | mk Y =>
      induction z using induction_on with
      | mk Z => simp only [mk_mul_mk]; exact mk_eq_mk_of_iso (α_ X Y Z)
      | zero => simp only [K₀.mul_zero]
      | add z z' h h' => simp only [K₀.mul_add, h, h']
      | neg z h => simp only [K₀.mul_neg, h]
    | zero => simp only [K₀.mul_zero, K₀.zero_mul]
    | add y y' h h' => simp only [K₀.mul_add, K₀.add_mul, h, h']
    | neg y h => simp only [K₀.mul_neg, K₀.neg_mul, h]
  | zero => simp only [K₀.zero_mul]
  | add x x' h h' => simp only [K₀.add_mul, h, h']
  | neg x h => simp only [K₀.neg_mul, h]

protected theorem one_mul (x : K₀ C) : 1 * x = x := by
  induction x using induction_on with
  | mk X => rw [one_def, mk_mul_mk]; exact mk_eq_mk_of_iso (λ_ X)
  | zero => exact K₀.mul_zero 1
  | add x x' h h' => rw [K₀.mul_add, h, h']
  | neg x h => rw [K₀.mul_neg, h]

protected theorem mul_one (x : K₀ C) : x * 1 = x := by
  induction x using induction_on with
  | mk X => rw [one_def, mk_mul_mk]; exact mk_eq_mk_of_iso (ρ_ X)
  | zero => exact K₀.zero_mul 1
  | add x x' h h' => rw [K₀.add_mul, h, h']
  | neg x h => rw [K₀.neg_mul, h]

/-- **Brundan–Ellis, §1.5.** For a monoidal additive category, `K₀` is a ring with
`[V] · [W] = [V ⊗ W]` and unit `[𝟙]`. -/
instance instRing : Ring (K₀ C) :=
  { (inferInstance : AddCommGroup (K₀ C)) with
    mul_assoc := K₀.mul_assoc
    one_mul := K₀.one_mul
    mul_one := K₀.mul_one
    left_distrib := K₀.mul_add
    right_distrib := K₀.add_mul
    zero_mul := K₀.zero_mul
    mul_zero := K₀.mul_zero }

end Ring

end K₀

/-! ## The ring `Zπ` -/

open Polynomial

/-- **Brundan–Ellis, §1.5.** The ring `Zπ := ℤ[π]/(π² − 1)`. -/
abbrev Zπ : Type := ℤ[X] ⧸ Ideal.span {(X ^ 2 - 1 : ℤ[X])}

namespace Zπ

/-- The generator `π ∈ Zπ`. -/
def π : Zπ := Ideal.Quotient.mk _ X

theorem π_mul_π : π * π = 1 := by
  rw [π, ← map_mul, ← sub_eq_zero, ← map_one (Ideal.Quotient.mk _), ← map_sub,
    Ideal.Quotient.eq_zero_iff_mem, ← pow_two]
  exact Ideal.subset_span rfl

theorem π_pow_two : π ^ 2 = 1 := by rw [pow_two, π_mul_π]

/-- Every element of `Zπ` is `a + b π` with `a b : ℤ`. -/
theorem exists_eq_add_mul_π (z : Zπ) : ∃ a b : ℤ, z = a + b * π := by
  obtain ⟨q, rfl⟩ := Ideal.Quotient.mk_surjective z
  induction q using Polynomial.induction_on with
  | C a => exact ⟨a, 0, by simp⟩
  | add p q hp hq =>
    obtain ⟨a, b, hab⟩ := hp
    obtain ⟨c, d, hcd⟩ := hq
    exact ⟨a + c, b + d, by rw [map_add, hab, hcd]; push_cast; ring⟩
  | monomial n a h =>
    obtain ⟨c, d, hcd⟩ := h
    refine ⟨d, c, ?_⟩
    have e : (Ideal.Quotient.mk _ (C a * X ^ (n + 1)) : Zπ) =
        Ideal.Quotient.mk _ (C a * X ^ n) * π := by
      rw [π, ← map_mul, mul_assoc, ← pow_succ]
    rw [e, hcd, add_mul, mul_assoc, π_mul_π, mul_one]
    ring

/-- The evaluation `Zπ → ℤ` at `π = ε` for `ε² = 1`. -/
def eval (ε : ℤ) (hε : ε * ε = 1) : Zπ →+* ℤ :=
  Ideal.Quotient.lift _ (eval₂RingHom (RingHom.id ℤ) ε) (by
    intro a ha
    obtain ⟨b, rfl⟩ := Ideal.mem_span_singleton'.1 ha
    simp [pow_two, hε])

theorem eval_π (ε : ℤ) (hε : ε * ε = 1) : eval ε hε π = ε := by
  simp [eval, π]

theorem eval_add_mul_π (ε : ℤ) (hε : ε * ε = 1) (a b : ℤ) :
    eval ε hε (a + b * π) = a + b * ε := by
  simp [eval_π]

/-- `1` and `π` are linearly independent over `ℤ`. -/
theorem add_mul_π_injective {a b c d : ℤ} (h : (a : Zπ) + b * π = c + d * π) : a = c ∧ b = d := by
  have h1 := congrArg (eval 1 (by norm_num)) h
  have h2 := congrArg (eval (-1) (by norm_num)) h
  rw [eval_add_mul_π, eval_add_mul_π] at h1 h2
  constructor <;> omega

variable {G : Type w} [AddCommGroup G]

/-- The ring homomorphism `Zπ → End(G)` sending `π` to an involution `σ`. -/
def toEnd (σ : AddMonoid.End G) (hσ : ∀ x, σ (σ x) = x) : Zπ →+* AddMonoid.End G :=
  Ideal.Quotient.lift _ (eval₂RingHom' (Int.castRingHom _) σ fun n => Int.cast_commute n σ)
    (by
      intro a ha
      obtain ⟨b, rfl⟩ := Ideal.mem_span_singleton'.1 ha
      rw [map_mul]
      convert mul_zero _
      change eval₂ (Int.castRingHom _) σ (X ^ 2 - 1) = 0
      rw [eval₂_sub, eval₂_X_pow, eval₂_one, sub_eq_zero, pow_two]
      exact DFunLike.ext _ _ hσ)

theorem toEnd_π (σ : AddMonoid.End G) (hσ : ∀ x, σ (σ x) = x) : toEnd σ hσ π = σ := by
  simp [toEnd, π, eval₂RingHom']

/-- The `Zπ`-module structure on an abelian group with an involution `σ`, with `π` acting by
`σ`. -/
def moduleOfInvolution (σ : AddMonoid.End G) (hσ : ∀ x, σ (σ x) = x) : Module Zπ G :=
  Module.compHom G (toEnd σ hσ)

theorem π_smul (σ : AddMonoid.End G) (hσ : ∀ x, σ (σ x) = x) (x : G) :
    letI := moduleOfInvolution σ hσ
    π • x = σ x := by
  change toEnd σ hσ π x = σ x
  rw [toEnd_π]

end Zπ

/-! ## The involution `π` of `K₀` of a Π-category -/

namespace K₀

variable (R : Type w) [CommRing R] (A : Type u) [Category.{v} A] [Preadditive A] [Linear R A]
  [PiCategory R A] [HasBinaryBiproducts A]

/-- **Brundan–Ellis, §1.5.** The involution `π([V]) := [Π V]` of `K₀` of a Π-category. -/
def piInvolution : K₀ A →+ K₀ A := map (PiCategory.pi (R := R) (C := A))

@[simp] theorem piInvolution_mk (X : A) :
    piInvolution R A (mk X) = mk ((PiCategory.pi (R := R)).obj X) := map_mk _ _

theorem piInvolution_piInvolution (x : K₀ A) : piInvolution R A (piInvolution R A x) = x := by
  rw [← AddMonoidHom.comp_apply, piInvolution, ← map_comp,
    map_eq_of_iso (PiCategory.ξ (R := R) (C := A)), map_id, AddMonoidHom.id_apply]

/-- **Brundan–Ellis, §1.5.** `K₀` of a Π-category is a module over `Zπ = ℤ[π]/(π² − 1)`, with
`π [V] = [Π V]`. -/
def moduleZπ : Module Zπ (K₀ A) :=
  Zπ.moduleOfInvolution (piInvolution R A) (piInvolution_piInvolution R A)

theorem π_smul_mk (X : A) :
    letI := moduleZπ R A
    Zπ.π • mk X = mk ((PiCategory.pi (R := R)).obj X) := by
  rw [Zπ.π_smul, piInvolution_mk]

end K₀

end StringDiagrams
